apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-soknadsdialog
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-soknadsdialog
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "{{base_path}}/api/isalive"
    initialDelay: 3
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "{{base_path}}/api/isready"
    initialDelay: 3
    timeout: 1
  prometheus:
    enabled: false
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: 600m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  ingresses:
    - {{ingress}}
  env:
    - name: SELF_URL
      value: {{ingress}}
    - name: NEXT_PUBLIC_BASE_PATH
      value: {{base_path}}
    - name: DEKORATOR_URL
      value: {{dekorator.url}}
    - name: DEKORATOR_ENV
      value: {{dekorator.env}}
    - name: LOGINSERVICE_URL
      value: {{loginservice.url}}
    - name: LOGINSERVICE_WELL_KNOWN_URL
      value: {{loginservice.wellKnown}}
    - name: NEXT_PUBLIC_SENTRY_STAGE
      value: {{sentry_stage}}
    - name: VEILARBPROXY_URL
      value: {{veilarbproxyUrl}}
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      autoLogin: true
      autoLoginIgnorePaths:
        - "{{base_path}}/api/*"
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: dev.dekoratoren.nav.no
      rules:
        - application: dp-soknad
        - application: dp-mellomlagring
