apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-soknadsdialog
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-soknadsdialog
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: "{{image}}"
  port: 3000
  liveness:
    path: "{{base_path}}/api/internal/isalive"
    initialDelay: 3
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "{{base_path}}/api/internal/isready"
    initialDelay: 3
    timeout: 1
  prometheus:
    enabled: true
    path: "{{base_path}}/api/internal/metrics"
  replicas:
    min: 4
    max: 6
    cpuThresholdPercentage: 80
  resources:
    limits:
      memory: 1280Mi
    requests:
      cpu: 50m
      memory: 256Mi
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  env:
    - name: NODE_OPTIONS
      value: "--max-old-space-size=1024"
    - name: SELF_URL
      value: "{{ingress}}"
    - name: NEXT_PUBLIC_BASE_PATH
      value: "{{base_path}}"
    - name: DEKORATOR_ENV
      value: "{{dekorator.env}}"
    - name: ARBEIDSSOKERREGISTERET_URL
      value: "{{arbeidssokerregisteretUrl}}"
    - name: ARBEIDSSOKERREGISTRERING_URL
      value: "{{arbeidssokerregistreringUrl}}"
    - name: NEXT_PUBLIC_SANITY_DATASET
      value: "{{sanity_dataset}}"
    - name: UNLEASH_SERVER_API_URL
      value: "{{unleash.url}}"
    - name: BRUKERDIALOG_URL
      value: "{{brukerdialogUrl}}"
  envFrom:
    - secret: dp-soknadsdialog-unleash-api-token
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      autoLogin: true
      autoLoginIgnorePaths:
        - "{{base_path}}/api/*"
        - "{{base_path}}/api/*/*"
        - "{{base_path}}/api/*/*/*"
        - "{{base_path}}/_next/static/*/*"
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: rt6o382n.apicdn.sanity.io
        - host: www.nav.no
        - host: teamdagpenger-unleash-api.nav.cloud.nais.io

      rules:
        - application: dp-soknad
        - application: dp-mellomlagring
        - application: paw-arbeidssoekerregisteret-api-oppslag-v2
          namespace: paw
        - application: nav-dekoratoren
          namespace: personbruker
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
