export const mockDokumentkravBesvart = {
  soknad_uuid: "8fbff721-73d7-456b-bba6-63916a122488",
  krav: [
    {
      id: "12",
      beskrivendeId: "faktum.dokument-hele-norge-bekreftelse-fra-relevant-fagpersonell",
      fakta: [
        {
          id: "6",
          svar: ["faktum.ikke-jobbe-hele-norge.svar.redusert-helse"],
          type: "flervalg",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.ikke-jobbe-hele-norge.svar.redusert-helse",
            "faktum.ikke-jobbe-hele-norge.svar.omsorg-baby",
            "faktum.ikke-jobbe-hele-norge.svar.eneansvar-barn",
            "faktum.ikke-jobbe-hele-norge.svar.omsorg-barn-spesielle-behov",
            "faktum.ikke-jobbe-hele-norge.svar.skift-turnus",
            "faktum.ikke-jobbe-hele-norge.svar.har-fylt-60",
            "faktum.ikke-jobbe-hele-norge.svar.annen-situasjon",
          ],
          beskrivendeId: "faktum.ikke-jobbe-hele-norge",
          sannsynliggjoresAv: [
            {
              id: "12",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-hele-norge-bekreftelse-fra-relevant-fagpersonell",
              sannsynliggjoresAv: [],
            },
          ],
        },
      ],
      filer: [
        {
          filnavn: "this_is_fine.jpg",
          filsti: "a725c786-5174-4dfb-9cf0-99febde02c96/12/36af8e4a-1775-441b-b862-3410c6a4467a",
          urn: "urn:vedlegg:a725c786-5174-4dfb-9cf0-99febde02c96/12/36af8e4a-1775-441b-b862-3410c6a4467a",
          storrelse: 53072,
          tidspunkt: "2022-10-14T13:22:12.003266+02:00",
          bundlet: true,
        },
        {
          filnavn: "test.jpeg",
          filsti: "a725c786-5174-4dfb-9cf0-99febde02c96/12/0fc48208-b4fa-4dbd-8aac-7891a13d456f",
          urn: "urn:vedlegg:a725c786-5174-4dfb-9cf0-99febde02c96/12/0fc48208-b4fa-4dbd-8aac-7891a13d456f",
          storrelse: 525924,
          tidspunkt: "2022-10-14T13:22:12.377083+02:00",
          bundlet: false,
        },
        {
          filnavn: "this-is-not-fine.jpeg",
          filsti: "a725c786-5174-4dfb-9cf0-99febde02c96/12/b958f84b-3844-4e86-890a-94f3790d1566",
          urn: "urn:vedlegg:a725c786-5174-4dfb-9cf0-99febde02c96/12/b958f84b-3844-4e86-890a-94f3790d1566",
          storrelse: 325892,
          tidspunkt: "2022-10-14T16:17:48.447438+02:00",
          bundlet: false,
        },
        {
          filnavn: "FDV - 2-pol jordfeilautomat.pdf",
          filsti: "a725c786-5174-4dfb-9cf0-99febde02c96/12/8d1abad0-c81b-45aa-a1c0-8723b63280b3",
          urn: "urn:vedlegg:a725c786-5174-4dfb-9cf0-99febde02c96/12/8d1abad0-c81b-45aa-a1c0-8723b63280b3",
          storrelse: 38311,
          tidspunkt: "2022-10-14T16:20:18.07299+02:00",
          bundlet: false,
        },
      ],
      gyldigeValg: [
        "dokumentkrav.svar.send.naa",
        "dokumentkrav.svar.send.senere",
        "dokumentkrav.svar.sendt.tidligere",
        "dokumentkrav.svar.sender.ikke",
        "dokumentkrav.svar.andre.sender",
      ],
      svar: "dokumentkrav.svar.send.naa",
      bundle:
        "urn:vedlegg:a725c786-5174-4dfb-9cf0-99febde02c96/125f179f-b03d-4437-92db-c4046bf12da0",
      bundleFilsti: "a725c786-5174-4dfb-9cf0-99febde02c96/125f179f-b03d-4437-92db-c4046bf12da0",
    },
    {
      id: "1014.3",
      beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
      fakta: [
        {
          id: "1002.3",
          svar: "asd",
          type: "tekst",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.barn-fornavn-mellomnavn",
          sannsynliggjoresAv: [
            {
              id: "1014.3",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
              sannsynliggjoresAv: [],
            },
          ],
        },
        {
          id: "1003.3",
          svar: "asd",
          type: "tekst",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.barn-etternavn",
          sannsynliggjoresAv: [
            {
              id: "1014.3",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
              sannsynliggjoresAv: [],
            },
          ],
        },
        {
          id: "1004.3",
          svar: "2022-10-01",
          type: "localdate",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.barn-foedselsdato",
          sannsynliggjoresAv: [
            {
              id: "1014.3",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
              sannsynliggjoresAv: [],
            },
          ],
        },
        {
          id: "1005.3",
          svar: "DZA",
          type: "land",
          roller: ["søker"],
          grupper: [],
          readOnly: false,
          gyldigeLand: [
            "AFG",
            "ALB",
            "DZA",
            "ASM",
            "AND",
            "AGO",
            "AIA",
            "ATA",
            "ATG",
            "ARG",
            "ARM",
            "ABW",
            "AZE",
            "AUS",
            "BHS",
            "BHR",
            "BGD",
            "BRB",
            "BEL",
            "BLZ",
            "BEN",
            "BMU",
            "BTN",
            "BOL",
            "BES",
            "BIH",
            "BWA",
            "BVT",
            "BRA",
            "BRN",
            "BGR",
            "BFA",
            "BDI",
            "CAN",
            "CYM",
            "CHL",
            "CXR",
            "COL",
            "COK",
            "CRI",
            "CUB",
            "CUW",
            "DNK",
            "ARE",
            "ATF",
            "PSE",
            "DOM",
            "CAF",
            "IOT",
            "DJI",
            "DMA",
            "ECU",
            "EGY",
            "GNQ",
            "CIV",
            "SLV",
            "ERI",
            "EST",
            "ETH",
            "FLK",
            "FJI",
            "PHL",
            "FIN",
            "FRA",
            "GUF",
            "PYF",
            "FRO",
            "GAB",
            "GMB",
            "GEO",
            "GHA",
            "GIB",
            "GRD",
            "GRL",
            "GLP",
            "GUM",
            "GTM",
            "GGY",
            "GIN",
            "GNB",
            "GUY",
            "HTI",
            "HMD",
            "GRC",
            "HND",
            "HKG",
            "BLR",
            "IND",
            "IDN",
            "IRQ",
            "IRN",
            "IRL",
            "ISL",
            "ISR",
            "ITA",
            "JAM",
            "JPN",
            "YEM",
            "JEY",
            "VIR",
            "VGB",
            "JOR",
            "KHM",
            "CMR",
            "CPV",
            "KAZ",
            "KEN",
            "CHN",
            "KGZ",
            "KIR",
            "CCK",
            "COM",
            "COD",
            "COG",
            "HRV",
            "KWT",
            "CYP",
            "LAO",
            "LVA",
            "LSO",
            "LBN",
            "LBR",
            "LBY",
            "LIE",
            "LTU",
            "LUX",
            "MAC",
            "MDG",
            "MKD",
            "MWI",
            "MYS",
            "MDV",
            "MLI",
            "MLT",
            "IMN",
            "MAR",
            "MHL",
            "MTQ",
            "MRT",
            "MUS",
            "MYT",
            "MEX",
            "FSM",
            "MDA",
            "MCO",
            "MNG",
            "MNE",
            "MSR",
            "MOZ",
            "MMR",
            "NAM",
            "NRU",
            "NPL",
            "NLD",
            "NZL",
            "NIC",
            "NER",
            "NGA",
            "NIU",
            "PRK",
            "MNP",
            "NFK",
            "NOR",
            "NCL",
            "OMN",
            "PAK",
            "PLW",
            "PAN",
            "PNG",
            "PRY",
            "PER",
            "PCN",
            "POL",
            "PRT",
            "PRI",
            "QAT",
            "REU",
            "ROU",
            "RUS",
            "RWA",
            "BLM",
            "SHN",
            "KNA",
            "LCA",
            "MAF",
            "SPM",
            "VCT",
            "SLB",
            "WSM",
            "SMR",
            "STP",
            "SAU",
            "SEN",
            "SRB",
            "SYC",
            "SLE",
            "SGP",
            "SXM",
            "SVK",
            "SVN",
            "SOM",
            "ESP",
            "LKA",
            "GBR",
            "SDN",
            "SUR",
            "SJM",
            "CHE",
            "SWE",
            "SWZ",
            "SYR",
            "ZAF",
            "SGS",
            "KOR",
            "SSD",
            "TJK",
            "TWN",
            "TZA",
            "THA",
            "TGO",
            "TKL",
            "TON",
            "TTO",
            "TCD",
            "CZE",
            "TUN",
            "TKM",
            "TCA",
            "TUV",
            "TUR",
            "DEU",
            "UGA",
            "UKR",
            "HUN",
            "URY",
            "USA",
            "UMI",
            "UZB",
            "VUT",
            "VAT",
            "VEN",
            "ESH",
            "VNM",
            "WLF",
            "ZMB",
            "ZWE",
            "AUT",
            "TLS",
            "ALA",
          ],
          beskrivendeId: "faktum.barn-statsborgerskap",
          sannsynliggjoresAv: [
            {
              id: "1014.3",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
              sannsynliggjoresAv: [],
            },
          ],
        },
      ],
      filer: [
        {
          filnavn: "this-is-not-fine.jpeg",
          filsti:
            "a725c786-5174-4dfb-9cf0-99febde02c96/1014.3/06eecb58-4599-4e6f-945b-5d67085b6c67",
          urn: "urn:vedlegg:a725c786-5174-4dfb-9cf0-99febde02c96/1014.3/06eecb58-4599-4e6f-945b-5d67085b6c67",
          storrelse: 325892,
          tidspunkt: "2022-10-14T16:17:09.515001+02:00",
          bundlet: false,
        },
        {
          filnavn: "test.jpeg",
          filsti:
            "a725c786-5174-4dfb-9cf0-99febde02c96/1014.3/d6f19754-d412-4371-9dfc-a4107b96c418",
          urn: "urn:vedlegg:a725c786-5174-4dfb-9cf0-99febde02c96/1014.3/d6f19754-d412-4371-9dfc-a4107b96c418",
          storrelse: 525924,
          tidspunkt: "2022-10-14T16:17:09.809281+02:00",
          bundlet: false,
        },
      ],
      gyldigeValg: [
        "dokumentkrav.svar.send.naa",
        "dokumentkrav.svar.send.senere",
        "dokumentkrav.svar.sendt.tidligere",
        "dokumentkrav.svar.sender.ikke",
        "dokumentkrav.svar.andre.sender",
      ],
      svar: "dokumentkrav.svar.send.naa",
      bundle:
        "urn:vedlegg:a725c786-5174-4dfb-9cf0-99febde02c96/205ae4ed-e17a-4573-908d-3a3a1e55b8e5",
      bundleFilsti: "a725c786-5174-4dfb-9cf0-99febde02c96/205ae4ed-e17a-4573-908d-3a3a1e55b8e5",
    },
    {
      id: "10",
      beskrivendeId: "faktum.dokument-bekreftelse-fra-lege-eller-annen-behandler",
      fakta: [
        {
          id: "8",
          svar: false,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: ["faktum.alle-typer-arbeid.svar.ja", "faktum.alle-typer-arbeid.svar.nei"],
          beskrivendeId: "faktum.alle-typer-arbeid",
          sannsynliggjoresAv: [
            {
              id: "10",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-bekreftelse-fra-lege-eller-annen-behandler",
              sannsynliggjoresAv: [],
            },
          ],
        },
      ],
      filer: [
        {
          filnavn: "this_is_fine.jpg",
          filsti: "a725c786-5174-4dfb-9cf0-99febde02c96/10/749d5ee1-eae7-40f6-a461-496fe5f57e1c",
          urn: "urn:vedlegg:a725c786-5174-4dfb-9cf0-99febde02c96/10/749d5ee1-eae7-40f6-a461-496fe5f57e1c",
          storrelse: 53072,
          tidspunkt: "2022-10-14T15:33:26.308012+02:00",
          bundlet: false,
        },
        {
          filnavn: "test.jpeg",
          filsti: "a725c786-5174-4dfb-9cf0-99febde02c96/10/d673aaf6-c1c7-491d-adb6-5dced09aaf58",
          urn: "urn:vedlegg:a725c786-5174-4dfb-9cf0-99febde02c96/10/d673aaf6-c1c7-491d-adb6-5dced09aaf58",
          storrelse: 525924,
          tidspunkt: "2022-10-14T15:33:27.176111+02:00",
          bundlet: false,
        },
        {
          filnavn: "this-is-not-fine.jpeg",
          filsti: "a725c786-5174-4dfb-9cf0-99febde02c96/10/6c21d069-1715-4133-93a3-0a1ab48c1582",
          urn: "urn:vedlegg:a725c786-5174-4dfb-9cf0-99febde02c96/10/6c21d069-1715-4133-93a3-0a1ab48c1582",
          storrelse: 325892,
          tidspunkt: "2022-10-14T16:16:33.548132+02:00",
          bundlet: false,
        },
      ],
      gyldigeValg: [
        "dokumentkrav.svar.send.naa",
        "dokumentkrav.svar.send.senere",
        "dokumentkrav.svar.sendt.tidligere",
        "dokumentkrav.svar.sender.ikke",
        "dokumentkrav.svar.andre.sender",
      ],
      svar: "dokumentkrav.svar.send.naa",
      bundle:
        "urn:vedlegg:a725c786-5174-4dfb-9cf0-99febde02c96/bb348f22-2a97-4471-992e-29adf434e55e",
      bundleFilsti: "a725c786-5174-4dfb-9cf0-99febde02c96/bb348f22-2a97-4471-992e-29adf434e55e",
    },
    {
      id: "1014.1",
      beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
      fakta: [
        {
          id: "1002.1",
          svar: "Tore",
          type: "tekst",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.barn-fornavn-mellomnavn",
          sannsynliggjoresAv: [
            {
              id: "1014.1",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
              sannsynliggjoresAv: [],
            },
          ],
        },
        {
          id: "1003.1",
          svar: "Tor",
          type: "tekst",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.barn-etternavn",
          sannsynliggjoresAv: [
            {
              id: "1014.1",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
              sannsynliggjoresAv: [],
            },
          ],
        },
        {
          id: "1004.1",
          svar: "2022-09-28",
          type: "localdate",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.barn-foedselsdato",
          sannsynliggjoresAv: [
            {
              id: "1014.1",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
              sannsynliggjoresAv: [],
            },
          ],
        },
        {
          id: "1005.1",
          svar: "DZA",
          type: "land",
          roller: ["søker"],
          grupper: [],
          readOnly: false,
          gyldigeLand: [
            "AFG",
            "ALB",
            "DZA",
            "ASM",
            "AND",
            "AGO",
            "AIA",
            "ATA",
            "ATG",
            "ARG",
            "ARM",
            "ABW",
            "AZE",
            "AUS",
            "BHS",
            "BHR",
            "BGD",
            "BRB",
            "BEL",
            "BLZ",
            "BEN",
            "BMU",
            "BTN",
            "BOL",
            "BES",
            "BIH",
            "BWA",
            "BVT",
            "BRA",
            "BRN",
            "BGR",
            "BFA",
            "BDI",
            "CAN",
            "CYM",
            "CHL",
            "CXR",
            "COL",
            "COK",
            "CRI",
            "CUB",
            "CUW",
            "DNK",
            "ARE",
            "ATF",
            "PSE",
            "DOM",
            "CAF",
            "IOT",
            "DJI",
            "DMA",
            "ECU",
            "EGY",
            "GNQ",
            "CIV",
            "SLV",
            "ERI",
            "EST",
            "ETH",
            "FLK",
            "FJI",
            "PHL",
            "FIN",
            "FRA",
            "GUF",
            "PYF",
            "FRO",
            "GAB",
            "GMB",
            "GEO",
            "GHA",
            "GIB",
            "GRD",
            "GRL",
            "GLP",
            "GUM",
            "GTM",
            "GGY",
            "GIN",
            "GNB",
            "GUY",
            "HTI",
            "HMD",
            "GRC",
            "HND",
            "HKG",
            "BLR",
            "IND",
            "IDN",
            "IRQ",
            "IRN",
            "IRL",
            "ISL",
            "ISR",
            "ITA",
            "JAM",
            "JPN",
            "YEM",
            "JEY",
            "VIR",
            "VGB",
            "JOR",
            "KHM",
            "CMR",
            "CPV",
            "KAZ",
            "KEN",
            "CHN",
            "KGZ",
            "KIR",
            "CCK",
            "COM",
            "COD",
            "COG",
            "HRV",
            "KWT",
            "CYP",
            "LAO",
            "LVA",
            "LSO",
            "LBN",
            "LBR",
            "LBY",
            "LIE",
            "LTU",
            "LUX",
            "MAC",
            "MDG",
            "MKD",
            "MWI",
            "MYS",
            "MDV",
            "MLI",
            "MLT",
            "IMN",
            "MAR",
            "MHL",
            "MTQ",
            "MRT",
            "MUS",
            "MYT",
            "MEX",
            "FSM",
            "MDA",
            "MCO",
            "MNG",
            "MNE",
            "MSR",
            "MOZ",
            "MMR",
            "NAM",
            "NRU",
            "NPL",
            "NLD",
            "NZL",
            "NIC",
            "NER",
            "NGA",
            "NIU",
            "PRK",
            "MNP",
            "NFK",
            "NOR",
            "NCL",
            "OMN",
            "PAK",
            "PLW",
            "PAN",
            "PNG",
            "PRY",
            "PER",
            "PCN",
            "POL",
            "PRT",
            "PRI",
            "QAT",
            "REU",
            "ROU",
            "RUS",
            "RWA",
            "BLM",
            "SHN",
            "KNA",
            "LCA",
            "MAF",
            "SPM",
            "VCT",
            "SLB",
            "WSM",
            "SMR",
            "STP",
            "SAU",
            "SEN",
            "SRB",
            "SYC",
            "SLE",
            "SGP",
            "SXM",
            "SVK",
            "SVN",
            "SOM",
            "ESP",
            "LKA",
            "GBR",
            "SDN",
            "SUR",
            "SJM",
            "CHE",
            "SWE",
            "SWZ",
            "SYR",
            "ZAF",
            "SGS",
            "KOR",
            "SSD",
            "TJK",
            "TWN",
            "TZA",
            "THA",
            "TGO",
            "TKL",
            "TON",
            "TTO",
            "TCD",
            "CZE",
            "TUN",
            "TKM",
            "TCA",
            "TUV",
            "TUR",
            "DEU",
            "UGA",
            "UKR",
            "HUN",
            "URY",
            "USA",
            "UMI",
            "UZB",
            "VUT",
            "VAT",
            "VEN",
            "ESH",
            "VNM",
            "WLF",
            "ZMB",
            "ZWE",
            "AUT",
            "TLS",
            "ALA",
          ],
          beskrivendeId: "faktum.barn-statsborgerskap",
          sannsynliggjoresAv: [
            {
              id: "1014.1",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
              sannsynliggjoresAv: [],
            },
          ],
        },
      ],
      filer: [],
      gyldigeValg: [
        "dokumentkrav.svar.send.naa",
        "dokumentkrav.svar.send.senere",
        "dokumentkrav.svar.sendt.tidligere",
        "dokumentkrav.svar.sender.ikke",
        "dokumentkrav.svar.andre.sender",
      ],
      begrunnelse: "234",
      svar: "dokumentkrav.svar.send.senere",
    },
    {
      id: "8055.1",
      beskrivendeId: "faktum.dokument-arbeidsavtale",
      fakta: [
        {
          id: "8006.1",
          svar: "faktum.arbeidsforhold.endret.svar.arbeidsgiver-konkurs",
          type: "envalg",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.arbeidsforhold.endret.svar.ikke-endret",
            "faktum.arbeidsforhold.endret.svar.avskjediget",
            "faktum.arbeidsforhold.endret.svar.sagt-opp-av-arbeidsgiver",
            "faktum.arbeidsforhold.endret.svar.arbeidsgiver-konkurs",
            "faktum.arbeidsforhold.endret.svar.kontrakt-utgaatt",
            "faktum.arbeidsforhold.endret.svar.sagt-opp-selv",
            "faktum.arbeidsforhold.endret.svar.redusert-arbeidstid",
            "faktum.arbeidsforhold.endret.svar.permittert",
          ],
          beskrivendeId: "faktum.arbeidsforhold.endret",
          sannsynliggjoresAv: [
            {
              id: "8055.1",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-arbeidsavtale",
              sannsynliggjoresAv: [],
            },
            {
              id: "8058.1",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-brev-fra-bobestyrer-eller-konkursforvalter",
              sannsynliggjoresAv: [],
            },
          ],
        },
      ],
      filer: [],
      gyldigeValg: [
        "dokumentkrav.svar.send.naa",
        "dokumentkrav.svar.send.senere",
        "dokumentkrav.svar.sendt.tidligere",
        "dokumentkrav.svar.sender.ikke",
        "dokumentkrav.svar.andre.sender",
      ],
      begrunnelse: "234",
      svar: "dokumentkrav.svar.send.senere",
    },
    {
      id: "8058.1",
      beskrivendeId: "faktum.dokument-brev-fra-bobestyrer-eller-konkursforvalter",
      fakta: [
        {
          id: "8006.1",
          svar: "faktum.arbeidsforhold.endret.svar.arbeidsgiver-konkurs",
          type: "envalg",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.arbeidsforhold.endret.svar.ikke-endret",
            "faktum.arbeidsforhold.endret.svar.avskjediget",
            "faktum.arbeidsforhold.endret.svar.sagt-opp-av-arbeidsgiver",
            "faktum.arbeidsforhold.endret.svar.arbeidsgiver-konkurs",
            "faktum.arbeidsforhold.endret.svar.kontrakt-utgaatt",
            "faktum.arbeidsforhold.endret.svar.sagt-opp-selv",
            "faktum.arbeidsforhold.endret.svar.redusert-arbeidstid",
            "faktum.arbeidsforhold.endret.svar.permittert",
          ],
          beskrivendeId: "faktum.arbeidsforhold.endret",
          sannsynliggjoresAv: [
            {
              id: "8055.1",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-arbeidsavtale",
              sannsynliggjoresAv: [],
            },
            {
              id: "8058.1",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-brev-fra-bobestyrer-eller-konkursforvalter",
              sannsynliggjoresAv: [],
            },
          ],
        },
      ],
      filer: [],
      gyldigeValg: [
        "dokumentkrav.svar.send.naa",
        "dokumentkrav.svar.send.senere",
        "dokumentkrav.svar.sendt.tidligere",
        "dokumentkrav.svar.sender.ikke",
        "dokumentkrav.svar.andre.sender",
      ],
      begrunnelse: "234",
      svar: "dokumentkrav.svar.send.senere",
    },
    {
      id: "1014.2",
      beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
      fakta: [
        {
          id: "1002.2",
          svar: "Tor",
          type: "tekst",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.barn-fornavn-mellomnavn",
          sannsynliggjoresAv: [
            {
              id: "1014.2",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
              sannsynliggjoresAv: [],
            },
          ],
        },
        {
          id: "1003.2",
          svar: "Tore",
          type: "tekst",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.barn-etternavn",
          sannsynliggjoresAv: [
            {
              id: "1014.2",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
              sannsynliggjoresAv: [],
            },
          ],
        },
        {
          id: "1004.2",
          svar: "2022-09-28",
          type: "localdate",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.barn-foedselsdato",
          sannsynliggjoresAv: [
            {
              id: "1014.2",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
              sannsynliggjoresAv: [],
            },
          ],
        },
        {
          id: "1005.2",
          svar: "ATA",
          type: "land",
          roller: ["søker"],
          grupper: [],
          readOnly: false,
          gyldigeLand: [
            "AFG",
            "ALB",
            "DZA",
            "ASM",
            "AND",
            "AGO",
            "AIA",
            "ATA",
            "ATG",
            "ARG",
            "ARM",
            "ABW",
            "AZE",
            "AUS",
            "BHS",
            "BHR",
            "BGD",
            "BRB",
            "BEL",
            "BLZ",
            "BEN",
            "BMU",
            "BTN",
            "BOL",
            "BES",
            "BIH",
            "BWA",
            "BVT",
            "BRA",
            "BRN",
            "BGR",
            "BFA",
            "BDI",
            "CAN",
            "CYM",
            "CHL",
            "CXR",
            "COL",
            "COK",
            "CRI",
            "CUB",
            "CUW",
            "DNK",
            "ARE",
            "ATF",
            "PSE",
            "DOM",
            "CAF",
            "IOT",
            "DJI",
            "DMA",
            "ECU",
            "EGY",
            "GNQ",
            "CIV",
            "SLV",
            "ERI",
            "EST",
            "ETH",
            "FLK",
            "FJI",
            "PHL",
            "FIN",
            "FRA",
            "GUF",
            "PYF",
            "FRO",
            "GAB",
            "GMB",
            "GEO",
            "GHA",
            "GIB",
            "GRD",
            "GRL",
            "GLP",
            "GUM",
            "GTM",
            "GGY",
            "GIN",
            "GNB",
            "GUY",
            "HTI",
            "HMD",
            "GRC",
            "HND",
            "HKG",
            "BLR",
            "IND",
            "IDN",
            "IRQ",
            "IRN",
            "IRL",
            "ISL",
            "ISR",
            "ITA",
            "JAM",
            "JPN",
            "YEM",
            "JEY",
            "VIR",
            "VGB",
            "JOR",
            "KHM",
            "CMR",
            "CPV",
            "KAZ",
            "KEN",
            "CHN",
            "KGZ",
            "KIR",
            "CCK",
            "COM",
            "COD",
            "COG",
            "HRV",
            "KWT",
            "CYP",
            "LAO",
            "LVA",
            "LSO",
            "LBN",
            "LBR",
            "LBY",
            "LIE",
            "LTU",
            "LUX",
            "MAC",
            "MDG",
            "MKD",
            "MWI",
            "MYS",
            "MDV",
            "MLI",
            "MLT",
            "IMN",
            "MAR",
            "MHL",
            "MTQ",
            "MRT",
            "MUS",
            "MYT",
            "MEX",
            "FSM",
            "MDA",
            "MCO",
            "MNG",
            "MNE",
            "MSR",
            "MOZ",
            "MMR",
            "NAM",
            "NRU",
            "NPL",
            "NLD",
            "NZL",
            "NIC",
            "NER",
            "NGA",
            "NIU",
            "PRK",
            "MNP",
            "NFK",
            "NOR",
            "NCL",
            "OMN",
            "PAK",
            "PLW",
            "PAN",
            "PNG",
            "PRY",
            "PER",
            "PCN",
            "POL",
            "PRT",
            "PRI",
            "QAT",
            "REU",
            "ROU",
            "RUS",
            "RWA",
            "BLM",
            "SHN",
            "KNA",
            "LCA",
            "MAF",
            "SPM",
            "VCT",
            "SLB",
            "WSM",
            "SMR",
            "STP",
            "SAU",
            "SEN",
            "SRB",
            "SYC",
            "SLE",
            "SGP",
            "SXM",
            "SVK",
            "SVN",
            "SOM",
            "ESP",
            "LKA",
            "GBR",
            "SDN",
            "SUR",
            "SJM",
            "CHE",
            "SWE",
            "SWZ",
            "SYR",
            "ZAF",
            "SGS",
            "KOR",
            "SSD",
            "TJK",
            "TWN",
            "TZA",
            "THA",
            "TGO",
            "TKL",
            "TON",
            "TTO",
            "TCD",
            "CZE",
            "TUN",
            "TKM",
            "TCA",
            "TUV",
            "TUR",
            "DEU",
            "UGA",
            "UKR",
            "HUN",
            "URY",
            "USA",
            "UMI",
            "UZB",
            "VUT",
            "VAT",
            "VEN",
            "ESH",
            "VNM",
            "WLF",
            "ZMB",
            "ZWE",
            "AUT",
            "TLS",
            "ALA",
          ],
          beskrivendeId: "faktum.barn-statsborgerskap",
          sannsynliggjoresAv: [
            {
              id: "1014.2",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-foedselsattest-bostedsbevis-for-barn-under-18aar",
              sannsynliggjoresAv: [],
            },
          ],
        },
      ],
      filer: [],
      gyldigeValg: [
        "dokumentkrav.svar.send.naa",
        "dokumentkrav.svar.send.senere",
        "dokumentkrav.svar.sendt.tidligere",
        "dokumentkrav.svar.sender.ikke",
        "dokumentkrav.svar.andre.sender",
      ],
      begrunnelse: "234",
      svar: "dokumentkrav.svar.send.senere",
    },
    {
      id: "8057.1",
      beskrivendeId: "faktum.dokument-timelister",
      fakta: [
        {
          id: "8045.1",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.arbeidsforhold.rotasjon.svar.ja",
            "faktum.arbeidsforhold.rotasjon.svar.nei",
          ],
          beskrivendeId: "faktum.arbeidsforhold.rotasjon",
          sannsynliggjoresAv: [
            {
              id: "8057.1",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-timelister",
              sannsynliggjoresAv: [],
            },
          ],
        },
      ],
      filer: [],
      gyldigeValg: [
        "dokumentkrav.svar.send.naa",
        "dokumentkrav.svar.send.senere",
        "dokumentkrav.svar.sendt.tidligere",
        "dokumentkrav.svar.sender.ikke",
        "dokumentkrav.svar.andre.sender",
      ],
      begrunnelse: "234",
      svar: "dokumentkrav.svar.send.senere",
    },
    {
      id: "7002",
      beskrivendeId:
        "faktum.dokument-avtjent-militaer-sivilforsvar-tjeneste-siste-12-mnd-dokumentasjon",
      fakta: [
        {
          id: "7001",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.avtjent-militaer-sivilforsvar-tjeneste-siste-12-mnd.svar.ja",
            "faktum.avtjent-militaer-sivilforsvar-tjeneste-siste-12-mnd.svar.nei",
          ],
          beskrivendeId: "faktum.avtjent-militaer-sivilforsvar-tjeneste-siste-12-mnd",
          sannsynliggjoresAv: [
            {
              id: "7002",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId:
                "faktum.dokument-avtjent-militaer-sivilforsvar-tjeneste-siste-12-mnd-dokumentasjon",
              sannsynliggjoresAv: [],
            },
          ],
        },
      ],
      filer: [],
      gyldigeValg: [
        "dokumentkrav.svar.send.naa",
        "dokumentkrav.svar.send.senere",
        "dokumentkrav.svar.sendt.tidligere",
        "dokumentkrav.svar.sender.ikke",
        "dokumentkrav.svar.andre.sender",
      ],
      begrunnelse: "",
      svar: "dokumentkrav.svar.send.senere",
    },
    {
      id: "11",
      beskrivendeId: "faktum.dokument-fulltid-bekreftelse-fra-relevant-fagpersonell",
      fakta: [
        {
          id: "2",
          svar: ["faktum.kun-deltid-aarsak.svar.redusert-helse"],
          type: "flervalg",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.kun-deltid-aarsak.svar.redusert-helse",
            "faktum.kun-deltid-aarsak.svar.omsorg-baby",
            "faktum.kun-deltid-aarsak.svar.eneansvar-barn",
            "faktum.kun-deltid-aarsak.svar.omsorg-barn-spesielle-behov",
            "faktum.kun-deltid-aarsak.svar.skift-turnus",
            "faktum.kun-deltid-aarsak.svar.har-fylt-60",
            "faktum.kun-deltid-aarsak.svar.annen-situasjon",
          ],
          beskrivendeId: "faktum.kun-deltid-aarsak",
          sannsynliggjoresAv: [
            {
              id: "11",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokument-fulltid-bekreftelse-fra-relevant-fagpersonell",
              sannsynliggjoresAv: [],
            },
          ],
        },
      ],
      filer: [],
      gyldigeValg: [
        "dokumentkrav.svar.send.naa",
        "dokumentkrav.svar.send.senere",
        "dokumentkrav.svar.sendt.tidligere",
        "dokumentkrav.svar.sender.ikke",
        "dokumentkrav.svar.andre.sender",
      ],
      begrunnelse: "234",
      svar: "dokumentkrav.svar.send.senere",
    },
  ],
};
