export const mockNeste = {
  "@id": "03e6cfa5-de02-4921-98e3-54555aa61db0",
  ferdig: true,
  seksjoner: [
    {
      fakta: [
        {
          id: "6001",
          svar: "NOR",
          type: "land",
          roller: ["søker"],
          grupper: [
            {
              land: [
                "AUT",
                "HUN",
                "DEU",
                "CZE",
                "SWE",
                "CHE",
                "ESP",
                "SVN",
                "SVK",
                "ROU",
                "PRT",
                "POL",
                "NLD",
                "MLT",
                "LUX",
                "LTU",
                "LIE",
                "LVA",
                "CYP",
                "HRV",
                "ITA",
                "ISL",
                "IRL",
                "GRC",
                "FRA",
                "FIN",
                "EST",
                "DNK",
                "BGR",
                "BEL",
              ],
              gruppeId: "faktum.hvilket-land-bor-du-i.gruppe.eøs",
            },
            {
              land: ["SJM", "NOR"],
              gruppeId: "faktum.hvilket-land-bor-du-i.gruppe.norge-jan-mayen",
            },
            {
              land: ["IMN", "JEY", "GBR"],
              gruppeId: "faktum.hvilket-land-bor-du-i.gruppe.storbritannia",
            },
          ],
          readOnly: false,
          gyldigeLand: [
            "AFG",
            "ALB",
            "DZA",
            "ASM",
            "AND",
            "AGO",
            "AIA",
            "ATA",
            "ATG",
            "ARG",
            "ARM",
            "ABW",
            "AZE",
            "AUS",
            "BHS",
            "BHR",
            "BGD",
            "BRB",
            "BEL",
            "BLZ",
            "BEN",
            "BMU",
            "BTN",
            "BOL",
            "BES",
            "BIH",
            "BWA",
            "BVT",
            "BRA",
            "BRN",
            "BGR",
            "BFA",
            "BDI",
            "CAN",
            "CYM",
            "CHL",
            "CXR",
            "COL",
            "COK",
            "CRI",
            "CUB",
            "CUW",
            "DNK",
            "ARE",
            "ATF",
            "PSE",
            "DOM",
            "CAF",
            "IOT",
            "DJI",
            "DMA",
            "ECU",
            "EGY",
            "GNQ",
            "CIV",
            "SLV",
            "ERI",
            "EST",
            "ETH",
            "FLK",
            "FJI",
            "PHL",
            "FIN",
            "FRA",
            "GUF",
            "PYF",
            "FRO",
            "GAB",
            "GMB",
            "GEO",
            "GHA",
            "GIB",
            "GRD",
            "GRL",
            "GLP",
            "GUM",
            "GTM",
            "GGY",
            "GIN",
            "GNB",
            "GUY",
            "HTI",
            "HMD",
            "GRC",
            "HND",
            "HKG",
            "BLR",
            "IND",
            "IDN",
            "IRQ",
            "IRN",
            "IRL",
            "ISL",
            "ISR",
            "ITA",
            "JAM",
            "JPN",
            "YEM",
            "JEY",
            "VIR",
            "VGB",
            "JOR",
            "KHM",
            "CMR",
            "CPV",
            "KAZ",
            "KEN",
            "CHN",
            "KGZ",
            "KIR",
            "CCK",
            "COM",
            "COD",
            "COG",
            "HRV",
            "KWT",
            "CYP",
            "LAO",
            "LVA",
            "LSO",
            "LBN",
            "LBR",
            "LBY",
            "LIE",
            "LTU",
            "LUX",
            "MAC",
            "MDG",
            "MKD",
            "MWI",
            "MYS",
            "MDV",
            "MLI",
            "MLT",
            "IMN",
            "MAR",
            "MHL",
            "MTQ",
            "MRT",
            "MUS",
            "MYT",
            "MEX",
            "FSM",
            "MDA",
            "MCO",
            "MNG",
            "MNE",
            "MSR",
            "MOZ",
            "MMR",
            "NAM",
            "NRU",
            "NPL",
            "NLD",
            "NZL",
            "NIC",
            "NER",
            "NGA",
            "NIU",
            "PRK",
            "MNP",
            "NFK",
            "NOR",
            "NCL",
            "OMN",
            "PAK",
            "PLW",
            "PAN",
            "PNG",
            "PRY",
            "PER",
            "PCN",
            "POL",
            "PRT",
            "PRI",
            "QAT",
            "REU",
            "ROU",
            "RUS",
            "RWA",
            "BLM",
            "SHN",
            "KNA",
            "LCA",
            "MAF",
            "SPM",
            "VCT",
            "SLB",
            "WSM",
            "SMR",
            "STP",
            "SAU",
            "SEN",
            "SRB",
            "SYC",
            "SLE",
            "SGP",
            "SXM",
            "SVK",
            "SVN",
            "SOM",
            "ESP",
            "LKA",
            "GBR",
            "SDN",
            "SUR",
            "SJM",
            "CHE",
            "SWE",
            "SWZ",
            "SYR",
            "ZAF",
            "SGS",
            "KOR",
            "SSD",
            "TJK",
            "TWN",
            "TZA",
            "THA",
            "TGO",
            "TKL",
            "TON",
            "TTO",
            "TCD",
            "CZE",
            "TUN",
            "TKM",
            "TCA",
            "TUV",
            "TUR",
            "DEU",
            "UGA",
            "UKR",
            "HUN",
            "URY",
            "USA",
            "UMI",
            "UZB",
            "VUT",
            "VAT",
            "VEN",
            "ESH",
            "VNM",
            "WLF",
            "ZMB",
            "ZWE",
            "AUT",
            "TLS",
            "ALA",
          ],
          beskrivendeId: "faktum.hvilket-land-bor-du-i",
          sannsynliggjoresAv: [],
        },
      ],
      ferdig: true,
      beskrivendeId: "bostedsland",
    },
    {
      fakta: [
        {
          id: "10001",
          svar: "faktum.mottatt-dagpenger-siste-12-mnd.svar.nei",
          type: "envalg",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.mottatt-dagpenger-siste-12-mnd.svar.ja",
            "faktum.mottatt-dagpenger-siste-12-mnd.svar.nei",
            "faktum.mottatt-dagpenger-siste-12-mnd.svar.vet-ikke",
          ],
          beskrivendeId: "faktum.mottatt-dagpenger-siste-12-mnd",
          sannsynliggjoresAv: [],
        },
      ],
      ferdig: true,
      beskrivendeId: "gjenopptak",
    },
    {
      fakta: [
        {
          id: "1008",
          svar: [
            [
              {
                id: "1009.1",
                svar: "LIKEGYLDIG",
                type: "tekst",
                roller: ["nav"],
                readOnly: true,
                beskrivendeId: "faktum.barn-fornavn-mellomnavn",
                sannsynliggjoresAv: [],
              },
              {
                id: "1010.1",
                svar: "BAGASJETRALLE",
                type: "tekst",
                roller: ["nav"],
                readOnly: true,
                beskrivendeId: "faktum.barn-etternavn",
                sannsynliggjoresAv: [],
              },
              {
                id: "1011.1",
                svar: "2009-11-23",
                type: "localdate",
                roller: ["nav"],
                readOnly: true,
                beskrivendeId: "faktum.barn-foedselsdato",
                sannsynliggjoresAv: [],
              },
              {
                id: "1012.1",
                svar: "NOR",
                type: "land",
                roller: ["nav"],
                grupper: [],
                readOnly: true,
                gyldigeLand: [
                  "AFG",
                  "ALB",
                  "DZA",
                  "ASM",
                  "AND",
                  "AGO",
                  "AIA",
                  "ATA",
                  "ATG",
                  "ARG",
                  "ARM",
                  "ABW",
                  "AZE",
                  "AUS",
                  "BHS",
                  "BHR",
                  "BGD",
                  "BRB",
                  "BEL",
                  "BLZ",
                  "BEN",
                  "BMU",
                  "BTN",
                  "BOL",
                  "BES",
                  "BIH",
                  "BWA",
                  "BVT",
                  "BRA",
                  "BRN",
                  "BGR",
                  "BFA",
                  "BDI",
                  "CAN",
                  "CYM",
                  "CHL",
                  "CXR",
                  "COL",
                  "COK",
                  "CRI",
                  "CUB",
                  "CUW",
                  "DNK",
                  "ARE",
                  "ATF",
                  "PSE",
                  "DOM",
                  "CAF",
                  "IOT",
                  "DJI",
                  "DMA",
                  "ECU",
                  "EGY",
                  "GNQ",
                  "CIV",
                  "SLV",
                  "ERI",
                  "EST",
                  "ETH",
                  "FLK",
                  "FJI",
                  "PHL",
                  "FIN",
                  "FRA",
                  "GUF",
                  "PYF",
                  "FRO",
                  "GAB",
                  "GMB",
                  "GEO",
                  "GHA",
                  "GIB",
                  "GRD",
                  "GRL",
                  "GLP",
                  "GUM",
                  "GTM",
                  "GGY",
                  "GIN",
                  "GNB",
                  "GUY",
                  "HTI",
                  "HMD",
                  "GRC",
                  "HND",
                  "HKG",
                  "BLR",
                  "IND",
                  "IDN",
                  "IRQ",
                  "IRN",
                  "IRL",
                  "ISL",
                  "ISR",
                  "ITA",
                  "JAM",
                  "JPN",
                  "YEM",
                  "JEY",
                  "VIR",
                  "VGB",
                  "JOR",
                  "KHM",
                  "CMR",
                  "CPV",
                  "KAZ",
                  "KEN",
                  "CHN",
                  "KGZ",
                  "KIR",
                  "CCK",
                  "COM",
                  "COD",
                  "COG",
                  "HRV",
                  "KWT",
                  "CYP",
                  "LAO",
                  "LVA",
                  "LSO",
                  "LBN",
                  "LBR",
                  "LBY",
                  "LIE",
                  "LTU",
                  "LUX",
                  "MAC",
                  "MDG",
                  "MKD",
                  "MWI",
                  "MYS",
                  "MDV",
                  "MLI",
                  "MLT",
                  "IMN",
                  "MAR",
                  "MHL",
                  "MTQ",
                  "MRT",
                  "MUS",
                  "MYT",
                  "MEX",
                  "FSM",
                  "MDA",
                  "MCO",
                  "MNG",
                  "MNE",
                  "MSR",
                  "MOZ",
                  "MMR",
                  "NAM",
                  "NRU",
                  "NPL",
                  "NLD",
                  "NZL",
                  "NIC",
                  "NER",
                  "NGA",
                  "NIU",
                  "PRK",
                  "MNP",
                  "NFK",
                  "NOR",
                  "NCL",
                  "OMN",
                  "PAK",
                  "PLW",
                  "PAN",
                  "PNG",
                  "PRY",
                  "PER",
                  "PCN",
                  "POL",
                  "PRT",
                  "PRI",
                  "QAT",
                  "REU",
                  "ROU",
                  "RUS",
                  "RWA",
                  "BLM",
                  "SHN",
                  "KNA",
                  "LCA",
                  "MAF",
                  "SPM",
                  "VCT",
                  "SLB",
                  "WSM",
                  "SMR",
                  "STP",
                  "SAU",
                  "SEN",
                  "SRB",
                  "SYC",
                  "SLE",
                  "SGP",
                  "SXM",
                  "SVK",
                  "SVN",
                  "SOM",
                  "ESP",
                  "LKA",
                  "GBR",
                  "SDN",
                  "SUR",
                  "SJM",
                  "CHE",
                  "SWE",
                  "SWZ",
                  "SYR",
                  "ZAF",
                  "SGS",
                  "KOR",
                  "SSD",
                  "TJK",
                  "TWN",
                  "TZA",
                  "THA",
                  "TGO",
                  "TKL",
                  "TON",
                  "TTO",
                  "TCD",
                  "CZE",
                  "TUN",
                  "TKM",
                  "TCA",
                  "TUV",
                  "TUR",
                  "DEU",
                  "UGA",
                  "UKR",
                  "HUN",
                  "URY",
                  "USA",
                  "UMI",
                  "UZB",
                  "VUT",
                  "VAT",
                  "VEN",
                  "ESH",
                  "VNM",
                  "WLF",
                  "ZMB",
                  "ZWE",
                  "AUT",
                  "TLS",
                  "ALA",
                ],
                beskrivendeId: "faktum.barn-statsborgerskap",
                sannsynliggjoresAv: [],
              },
              {
                id: "1013.1",
                svar: true,
                type: "boolean",
                roller: ["søker"],
                readOnly: false,
                gyldigeValg: [
                  "faktum.forsoerger-du-barnet.svar.ja",
                  "faktum.forsoerger-du-barnet.svar.nei",
                ],
                beskrivendeId: "faktum.forsoerger-du-barnet",
                sannsynliggjoresAv: [],
              },
            ],
            [
              {
                id: "1009.2",
                svar: "UTØRST",
                type: "tekst",
                roller: ["nav"],
                readOnly: true,
                beskrivendeId: "faktum.barn-fornavn-mellomnavn",
                sannsynliggjoresAv: [],
              },
              {
                id: "1010.2",
                svar: "FAKTURA",
                type: "tekst",
                roller: ["nav"],
                readOnly: true,
                beskrivendeId: "faktum.barn-etternavn",
                sannsynliggjoresAv: [],
              },
              {
                id: "1011.2",
                svar: "2014-06-02",
                type: "localdate",
                roller: ["nav"],
                readOnly: true,
                beskrivendeId: "faktum.barn-foedselsdato",
                sannsynliggjoresAv: [],
              },
              {
                id: "1012.2",
                svar: "NOR",
                type: "land",
                roller: ["nav"],
                grupper: [],
                readOnly: true,
                gyldigeLand: [
                  "AFG",
                  "ALB",
                  "DZA",
                  "ASM",
                  "AND",
                  "AGO",
                  "AIA",
                  "ATA",
                  "ATG",
                  "ARG",
                  "ARM",
                  "ABW",
                  "AZE",
                  "AUS",
                  "BHS",
                  "BHR",
                  "BGD",
                  "BRB",
                  "BEL",
                  "BLZ",
                  "BEN",
                  "BMU",
                  "BTN",
                  "BOL",
                  "BES",
                  "BIH",
                  "BWA",
                  "BVT",
                  "BRA",
                  "BRN",
                  "BGR",
                  "BFA",
                  "BDI",
                  "CAN",
                  "CYM",
                  "CHL",
                  "CXR",
                  "COL",
                  "COK",
                  "CRI",
                  "CUB",
                  "CUW",
                  "DNK",
                  "ARE",
                  "ATF",
                  "PSE",
                  "DOM",
                  "CAF",
                  "IOT",
                  "DJI",
                  "DMA",
                  "ECU",
                  "EGY",
                  "GNQ",
                  "CIV",
                  "SLV",
                  "ERI",
                  "EST",
                  "ETH",
                  "FLK",
                  "FJI",
                  "PHL",
                  "FIN",
                  "FRA",
                  "GUF",
                  "PYF",
                  "FRO",
                  "GAB",
                  "GMB",
                  "GEO",
                  "GHA",
                  "GIB",
                  "GRD",
                  "GRL",
                  "GLP",
                  "GUM",
                  "GTM",
                  "GGY",
                  "GIN",
                  "GNB",
                  "GUY",
                  "HTI",
                  "HMD",
                  "GRC",
                  "HND",
                  "HKG",
                  "BLR",
                  "IND",
                  "IDN",
                  "IRQ",
                  "IRN",
                  "IRL",
                  "ISL",
                  "ISR",
                  "ITA",
                  "JAM",
                  "JPN",
                  "YEM",
                  "JEY",
                  "VIR",
                  "VGB",
                  "JOR",
                  "KHM",
                  "CMR",
                  "CPV",
                  "KAZ",
                  "KEN",
                  "CHN",
                  "KGZ",
                  "KIR",
                  "CCK",
                  "COM",
                  "COD",
                  "COG",
                  "HRV",
                  "KWT",
                  "CYP",
                  "LAO",
                  "LVA",
                  "LSO",
                  "LBN",
                  "LBR",
                  "LBY",
                  "LIE",
                  "LTU",
                  "LUX",
                  "MAC",
                  "MDG",
                  "MKD",
                  "MWI",
                  "MYS",
                  "MDV",
                  "MLI",
                  "MLT",
                  "IMN",
                  "MAR",
                  "MHL",
                  "MTQ",
                  "MRT",
                  "MUS",
                  "MYT",
                  "MEX",
                  "FSM",
                  "MDA",
                  "MCO",
                  "MNG",
                  "MNE",
                  "MSR",
                  "MOZ",
                  "MMR",
                  "NAM",
                  "NRU",
                  "NPL",
                  "NLD",
                  "NZL",
                  "NIC",
                  "NER",
                  "NGA",
                  "NIU",
                  "PRK",
                  "MNP",
                  "NFK",
                  "NOR",
                  "NCL",
                  "OMN",
                  "PAK",
                  "PLW",
                  "PAN",
                  "PNG",
                  "PRY",
                  "PER",
                  "PCN",
                  "POL",
                  "PRT",
                  "PRI",
                  "QAT",
                  "REU",
                  "ROU",
                  "RUS",
                  "RWA",
                  "BLM",
                  "SHN",
                  "KNA",
                  "LCA",
                  "MAF",
                  "SPM",
                  "VCT",
                  "SLB",
                  "WSM",
                  "SMR",
                  "STP",
                  "SAU",
                  "SEN",
                  "SRB",
                  "SYC",
                  "SLE",
                  "SGP",
                  "SXM",
                  "SVK",
                  "SVN",
                  "SOM",
                  "ESP",
                  "LKA",
                  "GBR",
                  "SDN",
                  "SUR",
                  "SJM",
                  "CHE",
                  "SWE",
                  "SWZ",
                  "SYR",
                  "ZAF",
                  "SGS",
                  "KOR",
                  "SSD",
                  "TJK",
                  "TWN",
                  "TZA",
                  "THA",
                  "TGO",
                  "TKL",
                  "TON",
                  "TTO",
                  "TCD",
                  "CZE",
                  "TUN",
                  "TKM",
                  "TCA",
                  "TUV",
                  "TUR",
                  "DEU",
                  "UGA",
                  "UKR",
                  "HUN",
                  "URY",
                  "USA",
                  "UMI",
                  "UZB",
                  "VUT",
                  "VAT",
                  "VEN",
                  "ESH",
                  "VNM",
                  "WLF",
                  "ZMB",
                  "ZWE",
                  "AUT",
                  "TLS",
                  "ALA",
                ],
                beskrivendeId: "faktum.barn-statsborgerskap",
                sannsynliggjoresAv: [],
              },
              {
                id: "1013.2",
                svar: true,
                type: "boolean",
                roller: ["søker"],
                readOnly: false,
                gyldigeValg: [
                  "faktum.forsoerger-du-barnet.svar.ja",
                  "faktum.forsoerger-du-barnet.svar.nei",
                ],
                beskrivendeId: "faktum.forsoerger-du-barnet",
                sannsynliggjoresAv: [],
              },
            ],
          ],
          type: "generator",
          roller: ["nav"],
          readOnly: true,
          templates: [
            {
              id: "1009",
              type: "tekst",
              roller: ["nav"],
              beskrivendeId: "faktum.barn-fornavn-mellomnavn",
            },
            {
              id: "1010",
              type: "tekst",
              roller: ["nav"],
              beskrivendeId: "faktum.barn-etternavn",
            },
            {
              id: "1011",
              type: "localdate",
              roller: ["nav"],
              beskrivendeId: "faktum.barn-foedselsdato",
            },
            {
              id: "1012",
              type: "land",
              roller: ["nav"],
              beskrivendeId: "faktum.barn-statsborgerskap",
            },
            {
              id: "1013",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.forsoerger-du-barnet",
            },
          ],
          beskrivendeId: "faktum.register.barn-liste",
        },
        {
          id: "1007",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.legge-til-egne-barn.svar.ja",
            "faktum.legge-til-egne-barn.svar.nei",
          ],
          beskrivendeId: "faktum.legge-til-egne-barn",
          sannsynliggjoresAv: [],
        },
        {
          id: "1001",
          svar: [
            [
              {
                id: "1002.1",
                svar: "Hans",
                type: "tekst",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.barn-fornavn-mellomnavn",
                sannsynliggjoresAv: [
                  {
                    id: "1014.1",
                    type: "dokument",
                    roller: ["søker"],
                    readOnly: true,
                    beskrivendeId:
                      "faktum.dokumentasjon-foedselsattest-bostedsbevis-for-barn-under-18aar",
                    sannsynliggjoresAv: [],
                  },
                ],
              },
              {
                id: "1003.1",
                svar: "Frans",
                type: "tekst",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.barn-etternavn",
                sannsynliggjoresAv: [
                  {
                    id: "1014.1",
                    type: "dokument",
                    roller: ["søker"],
                    readOnly: true,
                    beskrivendeId:
                      "faktum.dokumentasjon-foedselsattest-bostedsbevis-for-barn-under-18aar",
                    sannsynliggjoresAv: [],
                  },
                ],
              },
              {
                id: "1004.1",
                svar: "2022-06-01",
                type: "localdate",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.barn-foedselsdato",
                sannsynliggjoresAv: [
                  {
                    id: "1014.1",
                    type: "dokument",
                    roller: ["søker"],
                    readOnly: true,
                    beskrivendeId:
                      "faktum.dokumentasjon-foedselsattest-bostedsbevis-for-barn-under-18aar",
                    sannsynliggjoresAv: [],
                  },
                ],
              },
              {
                id: "1005.1",
                svar: "NOR",
                type: "land",
                roller: ["søker"],
                grupper: [],
                readOnly: false,
                gyldigeLand: [
                  "AFG",
                  "ALB",
                  "DZA",
                  "ASM",
                  "AND",
                  "AGO",
                  "AIA",
                  "ATA",
                  "ATG",
                  "ARG",
                  "ARM",
                  "ABW",
                  "AZE",
                  "AUS",
                  "BHS",
                  "BHR",
                  "BGD",
                  "BRB",
                  "BEL",
                  "BLZ",
                  "BEN",
                  "BMU",
                  "BTN",
                  "BOL",
                  "BES",
                  "BIH",
                  "BWA",
                  "BVT",
                  "BRA",
                  "BRN",
                  "BGR",
                  "BFA",
                  "BDI",
                  "CAN",
                  "CYM",
                  "CHL",
                  "CXR",
                  "COL",
                  "COK",
                  "CRI",
                  "CUB",
                  "CUW",
                  "DNK",
                  "ARE",
                  "ATF",
                  "PSE",
                  "DOM",
                  "CAF",
                  "IOT",
                  "DJI",
                  "DMA",
                  "ECU",
                  "EGY",
                  "GNQ",
                  "CIV",
                  "SLV",
                  "ERI",
                  "EST",
                  "ETH",
                  "FLK",
                  "FJI",
                  "PHL",
                  "FIN",
                  "FRA",
                  "GUF",
                  "PYF",
                  "FRO",
                  "GAB",
                  "GMB",
                  "GEO",
                  "GHA",
                  "GIB",
                  "GRD",
                  "GRL",
                  "GLP",
                  "GUM",
                  "GTM",
                  "GGY",
                  "GIN",
                  "GNB",
                  "GUY",
                  "HTI",
                  "HMD",
                  "GRC",
                  "HND",
                  "HKG",
                  "BLR",
                  "IND",
                  "IDN",
                  "IRQ",
                  "IRN",
                  "IRL",
                  "ISL",
                  "ISR",
                  "ITA",
                  "JAM",
                  "JPN",
                  "YEM",
                  "JEY",
                  "VIR",
                  "VGB",
                  "JOR",
                  "KHM",
                  "CMR",
                  "CPV",
                  "KAZ",
                  "KEN",
                  "CHN",
                  "KGZ",
                  "KIR",
                  "CCK",
                  "COM",
                  "COD",
                  "COG",
                  "HRV",
                  "KWT",
                  "CYP",
                  "LAO",
                  "LVA",
                  "LSO",
                  "LBN",
                  "LBR",
                  "LBY",
                  "LIE",
                  "LTU",
                  "LUX",
                  "MAC",
                  "MDG",
                  "MKD",
                  "MWI",
                  "MYS",
                  "MDV",
                  "MLI",
                  "MLT",
                  "IMN",
                  "MAR",
                  "MHL",
                  "MTQ",
                  "MRT",
                  "MUS",
                  "MYT",
                  "MEX",
                  "FSM",
                  "MDA",
                  "MCO",
                  "MNG",
                  "MNE",
                  "MSR",
                  "MOZ",
                  "MMR",
                  "NAM",
                  "NRU",
                  "NPL",
                  "NLD",
                  "NZL",
                  "NIC",
                  "NER",
                  "NGA",
                  "NIU",
                  "PRK",
                  "MNP",
                  "NFK",
                  "NOR",
                  "NCL",
                  "OMN",
                  "PAK",
                  "PLW",
                  "PAN",
                  "PNG",
                  "PRY",
                  "PER",
                  "PCN",
                  "POL",
                  "PRT",
                  "PRI",
                  "QAT",
                  "REU",
                  "ROU",
                  "RUS",
                  "RWA",
                  "BLM",
                  "SHN",
                  "KNA",
                  "LCA",
                  "MAF",
                  "SPM",
                  "VCT",
                  "SLB",
                  "WSM",
                  "SMR",
                  "STP",
                  "SAU",
                  "SEN",
                  "SRB",
                  "SYC",
                  "SLE",
                  "SGP",
                  "SXM",
                  "SVK",
                  "SVN",
                  "SOM",
                  "ESP",
                  "LKA",
                  "GBR",
                  "SDN",
                  "SUR",
                  "SJM",
                  "CHE",
                  "SWE",
                  "SWZ",
                  "SYR",
                  "ZAF",
                  "SGS",
                  "KOR",
                  "SSD",
                  "TJK",
                  "TWN",
                  "TZA",
                  "THA",
                  "TGO",
                  "TKL",
                  "TON",
                  "TTO",
                  "TCD",
                  "CZE",
                  "TUN",
                  "TKM",
                  "TCA",
                  "TUV",
                  "TUR",
                  "DEU",
                  "UGA",
                  "UKR",
                  "HUN",
                  "URY",
                  "USA",
                  "UMI",
                  "UZB",
                  "VUT",
                  "VAT",
                  "VEN",
                  "ESH",
                  "VNM",
                  "WLF",
                  "ZMB",
                  "ZWE",
                  "AUT",
                  "TLS",
                  "ALA",
                ],
                beskrivendeId: "faktum.barn-statsborgerskap",
                sannsynliggjoresAv: [
                  {
                    id: "1014.1",
                    type: "dokument",
                    roller: ["søker"],
                    readOnly: true,
                    beskrivendeId:
                      "faktum.dokumentasjon-foedselsattest-bostedsbevis-for-barn-under-18aar",
                    sannsynliggjoresAv: [],
                  },
                ],
              },
              {
                id: "1006.1",
                svar: true,
                type: "boolean",
                roller: ["søker"],
                readOnly: false,
                gyldigeValg: [
                  "faktum.forsoerger-du-barnet.svar.ja",
                  "faktum.forsoerger-du-barnet.svar.nei",
                ],
                beskrivendeId: "faktum.forsoerger-du-barnet",
                sannsynliggjoresAv: [],
              },
            ],
          ],
          type: "generator",
          roller: ["søker"],
          readOnly: false,
          templates: [
            {
              id: "1002",
              type: "tekst",
              roller: ["søker"],
              beskrivendeId: "faktum.barn-fornavn-mellomnavn",
            },
            {
              id: "1003",
              type: "tekst",
              roller: ["søker"],
              beskrivendeId: "faktum.barn-etternavn",
            },
            {
              id: "1004",
              type: "localdate",
              roller: ["søker"],
              beskrivendeId: "faktum.barn-foedselsdato",
            },
            {
              id: "1005",
              type: "land",
              roller: ["søker"],
              beskrivendeId: "faktum.barn-statsborgerskap",
            },
            {
              id: "1006",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.forsoerger-du-barnet",
            },
            {
              id: "1014",
              type: "dokument",
              roller: ["søker"],
              beskrivendeId:
                "faktum.dokumentasjon-foedselsattest-bostedsbevis-for-barn-under-18aar",
            },
          ],
          beskrivendeId: "faktum.barn-liste",
        },
      ],
      ferdig: true,
      beskrivendeId: "barnetillegg",
    },
    {
      fakta: [
        {
          id: "8001",
          svar: "2021-11-01",
          type: "localdate",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.dagpenger-soknadsdato",
          sannsynliggjoresAv: [],
        },
        {
          id: "8002",
          svar: "faktum.type-arbeidstid.svar.fast",
          type: "envalg",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.type-arbeidstid.svar.fast",
            "faktum.type-arbeidstid.svar.varierende",
            "faktum.type-arbeidstid.svar.kombinasjon",
            "faktum.type-arbeidstid.svar.ingen-passer",
          ],
          beskrivendeId: "faktum.type-arbeidstid",
          sannsynliggjoresAv: [],
        },
        {
          id: "8003",
          svar: [
            [
              {
                id: "8004.1",
                svar: "Rema 1000",
                type: "tekst",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.arbeidsforhold.navn-bedrift",
                sannsynliggjoresAv: [],
              },
              {
                id: "8005.1",
                svar: "NOR",
                type: "land",
                roller: ["søker"],
                grupper: [],
                readOnly: false,
                gyldigeLand: [
                  "AFG",
                  "ALB",
                  "DZA",
                  "ASM",
                  "AND",
                  "AGO",
                  "AIA",
                  "ATA",
                  "ATG",
                  "ARG",
                  "ARM",
                  "ABW",
                  "AZE",
                  "AUS",
                  "BHS",
                  "BHR",
                  "BGD",
                  "BRB",
                  "BEL",
                  "BLZ",
                  "BEN",
                  "BMU",
                  "BTN",
                  "BOL",
                  "BES",
                  "BIH",
                  "BWA",
                  "BVT",
                  "BRA",
                  "BRN",
                  "BGR",
                  "BFA",
                  "BDI",
                  "CAN",
                  "CYM",
                  "CHL",
                  "CXR",
                  "COL",
                  "COK",
                  "CRI",
                  "CUB",
                  "CUW",
                  "DNK",
                  "ARE",
                  "ATF",
                  "PSE",
                  "DOM",
                  "CAF",
                  "IOT",
                  "DJI",
                  "DMA",
                  "ECU",
                  "EGY",
                  "GNQ",
                  "CIV",
                  "SLV",
                  "ERI",
                  "EST",
                  "ETH",
                  "FLK",
                  "FJI",
                  "PHL",
                  "FIN",
                  "FRA",
                  "GUF",
                  "PYF",
                  "FRO",
                  "GAB",
                  "GMB",
                  "GEO",
                  "GHA",
                  "GIB",
                  "GRD",
                  "GRL",
                  "GLP",
                  "GUM",
                  "GTM",
                  "GGY",
                  "GIN",
                  "GNB",
                  "GUY",
                  "HTI",
                  "HMD",
                  "GRC",
                  "HND",
                  "HKG",
                  "BLR",
                  "IND",
                  "IDN",
                  "IRQ",
                  "IRN",
                  "IRL",
                  "ISL",
                  "ISR",
                  "ITA",
                  "JAM",
                  "JPN",
                  "YEM",
                  "JEY",
                  "VIR",
                  "VGB",
                  "JOR",
                  "KHM",
                  "CMR",
                  "CPV",
                  "KAZ",
                  "KEN",
                  "CHN",
                  "KGZ",
                  "KIR",
                  "CCK",
                  "COM",
                  "COD",
                  "COG",
                  "HRV",
                  "KWT",
                  "CYP",
                  "LAO",
                  "LVA",
                  "LSO",
                  "LBN",
                  "LBR",
                  "LBY",
                  "LIE",
                  "LTU",
                  "LUX",
                  "MAC",
                  "MDG",
                  "MKD",
                  "MWI",
                  "MYS",
                  "MDV",
                  "MLI",
                  "MLT",
                  "IMN",
                  "MAR",
                  "MHL",
                  "MTQ",
                  "MRT",
                  "MUS",
                  "MYT",
                  "MEX",
                  "FSM",
                  "MDA",
                  "MCO",
                  "MNG",
                  "MNE",
                  "MSR",
                  "MOZ",
                  "MMR",
                  "NAM",
                  "NRU",
                  "NPL",
                  "NLD",
                  "NZL",
                  "NIC",
                  "NER",
                  "NGA",
                  "NIU",
                  "PRK",
                  "MNP",
                  "NFK",
                  "NOR",
                  "NCL",
                  "OMN",
                  "PAK",
                  "PLW",
                  "PAN",
                  "PNG",
                  "PRY",
                  "PER",
                  "PCN",
                  "POL",
                  "PRT",
                  "PRI",
                  "QAT",
                  "REU",
                  "ROU",
                  "RUS",
                  "RWA",
                  "BLM",
                  "SHN",
                  "KNA",
                  "LCA",
                  "MAF",
                  "SPM",
                  "VCT",
                  "SLB",
                  "WSM",
                  "SMR",
                  "STP",
                  "SAU",
                  "SEN",
                  "SRB",
                  "SYC",
                  "SLE",
                  "SGP",
                  "SXM",
                  "SVK",
                  "SVN",
                  "SOM",
                  "ESP",
                  "LKA",
                  "GBR",
                  "SDN",
                  "SUR",
                  "SJM",
                  "CHE",
                  "SWE",
                  "SWZ",
                  "SYR",
                  "ZAF",
                  "SGS",
                  "KOR",
                  "SSD",
                  "TJK",
                  "TWN",
                  "TZA",
                  "THA",
                  "TGO",
                  "TKL",
                  "TON",
                  "TTO",
                  "TCD",
                  "CZE",
                  "TUN",
                  "TKM",
                  "TCA",
                  "TUV",
                  "TUR",
                  "DEU",
                  "UGA",
                  "UKR",
                  "HUN",
                  "URY",
                  "USA",
                  "UMI",
                  "UZB",
                  "VUT",
                  "VAT",
                  "VEN",
                  "ESH",
                  "VNM",
                  "WLF",
                  "ZMB",
                  "ZWE",
                  "AUT",
                  "TLS",
                  "ALA",
                ],
                beskrivendeId: "faktum.arbeidsforhold.land",
                sannsynliggjoresAv: [],
              },
              {
                id: "8006.1",
                svar: "faktum.arbeidsforhold.endret.svar.avskjediget",
                type: "envalg",
                roller: ["søker"],
                readOnly: false,
                gyldigeValg: [
                  "faktum.arbeidsforhold.endret.svar.ikke-endret",
                  "faktum.arbeidsforhold.endret.svar.avskjediget",
                  "faktum.arbeidsforhold.endret.svar.sagt-opp-av-arbeidsgiver",
                  "faktum.arbeidsforhold.endret.svar.arbeidsgiver-konkurs",
                  "faktum.arbeidsforhold.endret.svar.kontrakt-utgaatt",
                  "faktum.arbeidsforhold.endret.svar.sagt-opp-selv",
                  "faktum.arbeidsforhold.endret.svar.redusert-arbeidstid",
                  "faktum.arbeidsforhold.endret.svar.permittert",
                ],
                beskrivendeId: "faktum.arbeidsforhold.endret",
                sannsynliggjoresAv: [
                  {
                    id: "8055.1",
                    type: "dokument",
                    roller: ["søker"],
                    readOnly: true,
                    beskrivendeId: "faktum.dokument-arbeidsavtale",
                    sannsynliggjoresAv: [],
                  },
                  {
                    id: "8056.1",
                    type: "dokument",
                    roller: ["søker"],
                    readOnly: true,
                    beskrivendeId: "faktum.dokument-dokumentasjon-av-arbeidsforhold",
                    sannsynliggjoresAv: [],
                  },
                ],
              },
              {
                id: "8017.1",
                svar: true,
                type: "boolean",
                roller: ["søker"],
                readOnly: false,
                gyldigeValg: [
                  "faktum.arbeidsforhold.vet-du-antall-timer-foer-mistet-jobb.svar.ja",
                  "faktum.arbeidsforhold.vet-du-antall-timer-foer-mistet-jobb.svar.nei",
                ],
                beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-mistet-jobb",
                sannsynliggjoresAv: [],
              },
              {
                id: "8023.1",
                svar: 40,
                type: "double",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.arbeidsforhold.antall-timer-dette-arbeidsforhold",
                sannsynliggjoresAv: [],
              },
              {
                id: "8039.1",
                svar: "Banket kollega",
                type: "tekst",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.arbeidsforhold.hva-er-aarsak-til-avskjediget",
                sannsynliggjoresAv: [],
              },
            ],
            [
              {
                id: "8004.2",
                svar: "Kiwi",
                type: "tekst",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.arbeidsforhold.navn-bedrift",
                sannsynliggjoresAv: [],
              },
              {
                id: "8005.2",
                svar: "DZA",
                type: "land",
                roller: ["søker"],
                grupper: [],
                readOnly: false,
                gyldigeLand: [
                  "AFG",
                  "ALB",
                  "DZA",
                  "ASM",
                  "AND",
                  "AGO",
                  "AIA",
                  "ATA",
                  "ATG",
                  "ARG",
                  "ARM",
                  "ABW",
                  "AZE",
                  "AUS",
                  "BHS",
                  "BHR",
                  "BGD",
                  "BRB",
                  "BEL",
                  "BLZ",
                  "BEN",
                  "BMU",
                  "BTN",
                  "BOL",
                  "BES",
                  "BIH",
                  "BWA",
                  "BVT",
                  "BRA",
                  "BRN",
                  "BGR",
                  "BFA",
                  "BDI",
                  "CAN",
                  "CYM",
                  "CHL",
                  "CXR",
                  "COL",
                  "COK",
                  "CRI",
                  "CUB",
                  "CUW",
                  "DNK",
                  "ARE",
                  "ATF",
                  "PSE",
                  "DOM",
                  "CAF",
                  "IOT",
                  "DJI",
                  "DMA",
                  "ECU",
                  "EGY",
                  "GNQ",
                  "CIV",
                  "SLV",
                  "ERI",
                  "EST",
                  "ETH",
                  "FLK",
                  "FJI",
                  "PHL",
                  "FIN",
                  "FRA",
                  "GUF",
                  "PYF",
                  "FRO",
                  "GAB",
                  "GMB",
                  "GEO",
                  "GHA",
                  "GIB",
                  "GRD",
                  "GRL",
                  "GLP",
                  "GUM",
                  "GTM",
                  "GGY",
                  "GIN",
                  "GNB",
                  "GUY",
                  "HTI",
                  "HMD",
                  "GRC",
                  "HND",
                  "HKG",
                  "BLR",
                  "IND",
                  "IDN",
                  "IRQ",
                  "IRN",
                  "IRL",
                  "ISL",
                  "ISR",
                  "ITA",
                  "JAM",
                  "JPN",
                  "YEM",
                  "JEY",
                  "VIR",
                  "VGB",
                  "JOR",
                  "KHM",
                  "CMR",
                  "CPV",
                  "KAZ",
                  "KEN",
                  "CHN",
                  "KGZ",
                  "KIR",
                  "CCK",
                  "COM",
                  "COD",
                  "COG",
                  "HRV",
                  "KWT",
                  "CYP",
                  "LAO",
                  "LVA",
                  "LSO",
                  "LBN",
                  "LBR",
                  "LBY",
                  "LIE",
                  "LTU",
                  "LUX",
                  "MAC",
                  "MDG",
                  "MKD",
                  "MWI",
                  "MYS",
                  "MDV",
                  "MLI",
                  "MLT",
                  "IMN",
                  "MAR",
                  "MHL",
                  "MTQ",
                  "MRT",
                  "MUS",
                  "MYT",
                  "MEX",
                  "FSM",
                  "MDA",
                  "MCO",
                  "MNG",
                  "MNE",
                  "MSR",
                  "MOZ",
                  "MMR",
                  "NAM",
                  "NRU",
                  "NPL",
                  "NLD",
                  "NZL",
                  "NIC",
                  "NER",
                  "NGA",
                  "NIU",
                  "PRK",
                  "MNP",
                  "NFK",
                  "NOR",
                  "NCL",
                  "OMN",
                  "PAK",
                  "PLW",
                  "PAN",
                  "PNG",
                  "PRY",
                  "PER",
                  "PCN",
                  "POL",
                  "PRT",
                  "PRI",
                  "QAT",
                  "REU",
                  "ROU",
                  "RUS",
                  "RWA",
                  "BLM",
                  "SHN",
                  "KNA",
                  "LCA",
                  "MAF",
                  "SPM",
                  "VCT",
                  "SLB",
                  "WSM",
                  "SMR",
                  "STP",
                  "SAU",
                  "SEN",
                  "SRB",
                  "SYC",
                  "SLE",
                  "SGP",
                  "SXM",
                  "SVK",
                  "SVN",
                  "SOM",
                  "ESP",
                  "LKA",
                  "GBR",
                  "SDN",
                  "SUR",
                  "SJM",
                  "CHE",
                  "SWE",
                  "SWZ",
                  "SYR",
                  "ZAF",
                  "SGS",
                  "KOR",
                  "SSD",
                  "TJK",
                  "TWN",
                  "TZA",
                  "THA",
                  "TGO",
                  "TKL",
                  "TON",
                  "TTO",
                  "TCD",
                  "CZE",
                  "TUN",
                  "TKM",
                  "TCA",
                  "TUV",
                  "TUR",
                  "DEU",
                  "UGA",
                  "UKR",
                  "HUN",
                  "URY",
                  "USA",
                  "UMI",
                  "UZB",
                  "VUT",
                  "VAT",
                  "VEN",
                  "ESH",
                  "VNM",
                  "WLF",
                  "ZMB",
                  "ZWE",
                  "AUT",
                  "TLS",
                  "ALA",
                ],
                beskrivendeId: "faktum.arbeidsforhold.land",
                sannsynliggjoresAv: [],
              },
              {
                id: "8006.2",
                svar: "faktum.arbeidsforhold.endret.svar.permittert",
                type: "envalg",
                roller: ["søker"],
                readOnly: false,
                gyldigeValg: [
                  "faktum.arbeidsforhold.endret.svar.ikke-endret",
                  "faktum.arbeidsforhold.endret.svar.avskjediget",
                  "faktum.arbeidsforhold.endret.svar.sagt-opp-av-arbeidsgiver",
                  "faktum.arbeidsforhold.endret.svar.arbeidsgiver-konkurs",
                  "faktum.arbeidsforhold.endret.svar.kontrakt-utgaatt",
                  "faktum.arbeidsforhold.endret.svar.sagt-opp-selv",
                  "faktum.arbeidsforhold.endret.svar.redusert-arbeidstid",
                  "faktum.arbeidsforhold.endret.svar.permittert",
                ],
                beskrivendeId: "faktum.arbeidsforhold.endret",
                sannsynliggjoresAv: [
                  {
                    id: "8060.2",
                    type: "dokument",
                    roller: ["søker"],
                    readOnly: true,
                    beskrivendeId: "faktum.dokument-permitteringsvarsel",
                    sannsynliggjoresAv: [],
                  },
                ],
              },
              {
                id: "8012.2",
                svar: "faktum.arbeidsforhold.midlertidig-med-kontraktfestet-sluttdato.svar.ja",
                type: "envalg",
                roller: ["søker"],
                readOnly: false,
                gyldigeValg: [
                  "faktum.arbeidsforhold.midlertidig-med-kontraktfestet-sluttdato.svar.ja",
                  "faktum.arbeidsforhold.midlertidig-med-kontraktfestet-sluttdato.svar.nei",
                  "faktum.arbeidsforhold.midlertidig-med-kontraktfestet-sluttdato.svar.vet-ikke",
                ],
                beskrivendeId: "faktum.arbeidsforhold.midlertidig-med-kontraktfestet-sluttdato",
                sannsynliggjoresAv: [],
              },
              {
                id: "8013.2",
                svar: "2023-01-02",
                type: "localdate",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.arbeidsforhold.kontraktfestet-sluttdato",
                sannsynliggjoresAv: [],
              },
              {
                id: "8014.2",
                svar: "2022-02-01",
                type: "localdate",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.arbeidsforhold.midlertidig-arbeidsforhold-oppstartsdato",
                sannsynliggjoresAv: [],
              },
              {
                id: "8015.2",
                svar: true,
                type: "boolean",
                roller: ["søker"],
                readOnly: false,
                gyldigeValg: [
                  "faktum.arbeidsforhold.permittertert-fra-fiskeri-naering.svar.ja",
                  "faktum.arbeidsforhold.permittertert-fra-fiskeri-naering.svar.nei",
                ],
                beskrivendeId: "faktum.arbeidsforhold.permittertert-fra-fiskeri-naering",
                sannsynliggjoresAv: [],
              },
              {
                id: "8022.2",
                svar: false,
                type: "boolean",
                roller: ["søker"],
                readOnly: false,
                gyldigeValg: [
                  "faktum.arbeidsforhold.vet-du-antall-timer-foer-permittert.svar.ja",
                  "faktum.arbeidsforhold.vet-du-antall-timer-foer-permittert.svar.nei",
                ],
                beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-permittert",
                sannsynliggjoresAv: [],
              },
              {
                id: "8024.2",
                svar: {
                  fom: "2022-10-01",
                  tom: "2022-10-30",
                },
                type: "periode",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.arbeidsforhold.permittert-periode",
                sannsynliggjoresAv: [],
              },
              {
                id: "8025.2",
                svar: 36,
                type: "int",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.arbeidsforhold.permittert-prosent",
                sannsynliggjoresAv: [],
              },
              {
                id: "8026.2",
                svar: false,
                type: "boolean",
                roller: ["søker"],
                readOnly: false,
                gyldigeValg: [
                  "faktum.arbeidsforhold.vet-du-lonnsplikt-periode.svar.ja",
                  "faktum.arbeidsforhold.vet-du-lonnsplikt-periode.svar.nei",
                ],
                beskrivendeId: "faktum.arbeidsforhold.vet-du-lonnsplikt-periode",
                sannsynliggjoresAv: [],
              },
              {
                id: "8044.2",
                svar: true,
                type: "boolean",
                roller: ["søker"],
                readOnly: false,
                gyldigeValg: [
                  "faktum.arbeidsforhold.skift-eller-turnus.svar.ja",
                  "faktum.arbeidsforhold.skift-eller-turnus.svar.nei",
                ],
                beskrivendeId: "faktum.arbeidsforhold.skift-eller-turnus",
                sannsynliggjoresAv: [],
              },
              {
                id: "8045.2",
                svar: true,
                type: "boolean",
                roller: ["søker"],
                readOnly: false,
                gyldigeValg: [
                  "faktum.arbeidsforhold.rotasjon.svar.ja",
                  "faktum.arbeidsforhold.rotasjon.svar.nei",
                ],
                beskrivendeId: "faktum.arbeidsforhold.rotasjon",
                sannsynliggjoresAv: [
                  {
                    id: "8057.2",
                    type: "dokument",
                    roller: ["søker"],
                    readOnly: true,
                    beskrivendeId: "faktum.dokument-timelister",
                    sannsynliggjoresAv: [],
                  },
                ],
              },
              {
                id: "8046.2",
                svar: 25,
                type: "int",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.arbeidsforhold.arbeidsdager-siste-rotasjon",
                sannsynliggjoresAv: [],
              },
              {
                id: "8047.2",
                svar: 2,
                type: "int",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.arbeidsforhold.fridager-siste-rotasjon",
                sannsynliggjoresAv: [],
              },
            ],
          ],
          type: "generator",
          roller: ["søker"],
          readOnly: false,
          templates: [
            {
              id: "8004",
              type: "tekst",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.navn-bedrift",
            },
            {
              id: "8005",
              type: "land",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.land",
            },
            {
              id: "8006",
              type: "envalg",
              roller: ["søker"],
              gyldigeValg: [
                "faktum.arbeidsforhold.endret.svar.ikke-endret",
                "faktum.arbeidsforhold.endret.svar.avskjediget",
                "faktum.arbeidsforhold.endret.svar.sagt-opp-av-arbeidsgiver",
                "faktum.arbeidsforhold.endret.svar.arbeidsgiver-konkurs",
                "faktum.arbeidsforhold.endret.svar.kontrakt-utgaatt",
                "faktum.arbeidsforhold.endret.svar.sagt-opp-selv",
                "faktum.arbeidsforhold.endret.svar.redusert-arbeidstid",
                "faktum.arbeidsforhold.endret.svar.permittert",
              ],
              beskrivendeId: "faktum.arbeidsforhold.endret",
            },
            {
              id: "8007",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.kjent-antall-timer-jobbet",
            },
            {
              id: "8008",
              type: "double",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.antall-timer-jobbet",
            },
            {
              id: "8048",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.har-tilleggsopplysninger",
            },
            {
              id: "8009",
              type: "tekst",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.tilleggsopplysninger",
            },
            {
              id: "8010",
              type: "localdate",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.startdato-arbeidsforhold",
            },
            {
              id: "8011",
              type: "localdate",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.arbeidstid-redusert-fra-dato",
            },
            {
              id: "8012",
              type: "envalg",
              roller: ["søker"],
              gyldigeValg: [
                "faktum.arbeidsforhold.midlertidig-med-kontraktfestet-sluttdato.svar.ja",
                "faktum.arbeidsforhold.midlertidig-med-kontraktfestet-sluttdato.svar.nei",
                "faktum.arbeidsforhold.midlertidig-med-kontraktfestet-sluttdato.svar.vet-ikke",
              ],
              beskrivendeId: "faktum.arbeidsforhold.midlertidig-med-kontraktfestet-sluttdato",
            },
            {
              id: "8013",
              type: "localdate",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.kontraktfestet-sluttdato",
            },
            {
              id: "8014",
              type: "localdate",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.midlertidig-arbeidsforhold-oppstartsdato",
            },
            {
              id: "8015",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.permittertert-fra-fiskeri-naering",
            },
            {
              id: "8016",
              type: "periode",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.varighet",
            },
            {
              id: "8042",
              type: "envalg",
              roller: ["søker"],
              gyldigeValg: [
                "faktum.arbeidsforhold.midlertidig-arbeidsforhold-med-sluttdato.svar.ja",
                "faktum.arbeidsforhold.midlertidig-arbeidsforhold-med-sluttdato.svar.nei",
                "faktum.arbeidsforhold.midlertidig-arbeidsforhold-med-sluttdato.svar.vet-ikke",
              ],
              beskrivendeId: "faktum.arbeidsforhold.midlertidig-arbeidsforhold-med-sluttdato",
            },
            {
              id: "8017",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-mistet-jobb",
            },
            {
              id: "8018",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-konkurs",
            },
            {
              id: "8019",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-kontrakt-utgikk",
            },
            {
              id: "8020",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-du-sa-opp",
            },
            {
              id: "8021",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-redusert-arbeidstid",
            },
            {
              id: "8022",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-permittert",
            },
            {
              id: "8023",
              type: "double",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.antall-timer-dette-arbeidsforhold",
            },
            {
              id: "8024",
              type: "periode",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.permittert-periode",
            },
            {
              id: "8025",
              type: "int",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.permittert-prosent",
            },
            {
              id: "8026",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.vet-du-lonnsplikt-periode",
            },
            {
              id: "8027",
              type: "periode",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.naar-var-lonnsplikt-periode",
            },
            {
              id: "8028",
              type: "tekst",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.aarsak-til-du-sa-opp",
            },
            {
              id: "8029",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.tilbud-om-forlengelse-eller-annen-stilling",
            },
            {
              id: "8030",
              type: "envalg",
              roller: ["søker"],
              gyldigeValg: [
                "faktum.arbeidsforhold.svar-paa-forlengelse-eller-annen-stilling.svar.ja",
                "faktum.arbeidsforhold.svar-paa-forlengelse-eller-annen-stilling.svar.nei",
                "faktum.arbeidsforhold.svar-paa-forlengelse-eller-annen-stilling.svar.ikke-svart",
              ],
              beskrivendeId: "faktum.arbeidsforhold.svar-paa-forlengelse-eller-annen-stilling",
            },
            {
              id: "8031",
              type: "tekst",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.aarsak-til-ikke-akseptert-tilbud",
            },
            {
              id: "8032",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.soke-forskudd-lonnsgarantimidler",
            },
            {
              id: "8033",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId:
                "faktum.arbeidsforhold.soke-forskudd-lonnsgarantimidler-i-tillegg-til-dagpenger",
            },
            {
              id: "8034",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId:
                "faktum.arbeidsforhold.godta-trekk-fra-nav-av-forskudd-fra-lonnsgarantimidler",
            },
            {
              id: "8035",
              type: "envalg",
              roller: ["søker"],
              gyldigeValg: [
                "faktum.arbeidsforhold.har-sokt-om-lonnsgarantimidler.svar.nei",
                "faktum.arbeidsforhold.har-sokt-om-lonnsgarantimidler.svar.nei-men-skal",
                "faktum.arbeidsforhold.har-sokt-om-lonnsgarantimidler.svar.ja",
              ],
              beskrivendeId: "faktum.arbeidsforhold.har-sokt-om-lonnsgarantimidler",
            },
            {
              id: "8036",
              type: "envalg",
              roller: ["søker"],
              gyldigeValg: [
                "faktum.arbeidsforhold.dekker-lonnsgarantiordningen-lonnskravet-ditt.svar.ja",
                "faktum.arbeidsforhold.dekker-lonnsgarantiordningen-lonnskravet-ditt.svar.nei",
                "faktum.arbeidsforhold.dekker-lonnsgarantiordningen-lonnskravet-ditt.svar.vet-ikke",
              ],
              beskrivendeId: "faktum.arbeidsforhold.dekker-lonnsgarantiordningen-lonnskravet-ditt",
            },
            {
              id: "8037",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.utbetalt-lonn-etter-konkurs",
            },
            {
              id: "8038",
              type: "localdate",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.siste-dag-utbetalt-for-konkurs",
            },
            {
              id: "8039",
              type: "tekst",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.hva-er-aarsak-til-avskjediget",
            },
            {
              id: "8040",
              type: "tekst",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.vet-du-aarsak-til-sagt-opp-av-arbeidsgiver",
            },
            {
              id: "8041",
              type: "tekst",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.vet-du-aarsak-til-redusert-arbeidstid",
            },
            {
              id: "8043",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId:
                "faktum.arbeidsforhold.tilbud-om-annen-stilling-eller-annet-sted-i-norge",
            },
            {
              id: "8044",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.skift-eller-turnus",
            },
            {
              id: "8045",
              type: "boolean",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.rotasjon",
            },
            {
              id: "8046",
              type: "int",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.arbeidsdager-siste-rotasjon",
            },
            {
              id: "8047",
              type: "int",
              roller: ["søker"],
              beskrivendeId: "faktum.arbeidsforhold.fridager-siste-rotasjon",
            },
            {
              id: "8055",
              type: "dokument",
              roller: ["søker"],
              beskrivendeId: "faktum.dokument-arbeidsavtale",
            },
            {
              id: "8056",
              type: "dokument",
              roller: ["søker"],
              beskrivendeId: "faktum.dokument-dokumentasjon-av-arbeidsforhold",
            },
            {
              id: "8058",
              type: "dokument",
              roller: ["søker"],
              beskrivendeId: "faktum.dokument-brev-fra-bobestyrer-eller-konkursforvalter",
            },
            {
              id: "8060",
              type: "dokument",
              roller: ["søker"],
              beskrivendeId: "faktum.dokument-permitteringsvarsel",
            },
            {
              id: "8057",
              type: "dokument",
              roller: ["søker"],
              beskrivendeId: "faktum.dokument-timelister",
            },
            {
              id: "8059",
              type: "dokument",
              roller: ["søker"],
              beskrivendeId: "faktum.dokument-ny-arbeidsavtale",
            },
          ],
          beskrivendeId: "faktum.arbeidsforhold",
        },
      ],
      ferdig: true,
      beskrivendeId: "arbeidsforhold",
    },
    {
      fakta: [
        {
          id: "9001",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.eos-arbeid-siste-36-mnd.svar.ja",
            "faktum.eos-arbeid-siste-36-mnd.svar.nei",
          ],
          beskrivendeId: "faktum.eos-arbeid-siste-36-mnd",
          sannsynliggjoresAv: [],
        },
        {
          id: "9002",
          svar: [
            [
              {
                id: "9003.1",
                svar: "Krankenhause",
                type: "tekst",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.eos-arbeidsforhold.arbeidsgivernavn",
                sannsynliggjoresAv: [],
              },
              {
                id: "9004.1",
                svar: "DEU",
                type: "land",
                roller: ["søker"],
                grupper: [
                  {
                    land: [
                      "AUT",
                      "HUN",
                      "DEU",
                      "CZE",
                      "SWE",
                      "CHE",
                      "ESP",
                      "SVN",
                      "SVK",
                      "ROU",
                      "PRT",
                      "POL",
                      "NLD",
                      "MLT",
                      "LUX",
                      "LTU",
                      "LIE",
                      "LVA",
                      "CYP",
                      "HRV",
                      "ITA",
                      "ISL",
                      "IRL",
                      "GRC",
                      "FRA",
                      "FIN",
                      "EST",
                      "DNK",
                      "BGR",
                      "BEL",
                    ],
                    gruppeId: "faktum.eos-arbeidsforhold.land.gruppe.eøs",
                  },
                ],
                readOnly: false,
                gyldigeLand: [
                  "AFG",
                  "ALB",
                  "DZA",
                  "ASM",
                  "AND",
                  "AGO",
                  "AIA",
                  "ATA",
                  "ATG",
                  "ARG",
                  "ARM",
                  "ABW",
                  "AZE",
                  "AUS",
                  "BHS",
                  "BHR",
                  "BGD",
                  "BRB",
                  "BEL",
                  "BLZ",
                  "BEN",
                  "BMU",
                  "BTN",
                  "BOL",
                  "BES",
                  "BIH",
                  "BWA",
                  "BVT",
                  "BRA",
                  "BRN",
                  "BGR",
                  "BFA",
                  "BDI",
                  "CAN",
                  "CYM",
                  "CHL",
                  "CXR",
                  "COL",
                  "COK",
                  "CRI",
                  "CUB",
                  "CUW",
                  "DNK",
                  "ARE",
                  "ATF",
                  "PSE",
                  "DOM",
                  "CAF",
                  "IOT",
                  "DJI",
                  "DMA",
                  "ECU",
                  "EGY",
                  "GNQ",
                  "CIV",
                  "SLV",
                  "ERI",
                  "EST",
                  "ETH",
                  "FLK",
                  "FJI",
                  "PHL",
                  "FIN",
                  "FRA",
                  "GUF",
                  "PYF",
                  "FRO",
                  "GAB",
                  "GMB",
                  "GEO",
                  "GHA",
                  "GIB",
                  "GRD",
                  "GRL",
                  "GLP",
                  "GUM",
                  "GTM",
                  "GGY",
                  "GIN",
                  "GNB",
                  "GUY",
                  "HTI",
                  "HMD",
                  "GRC",
                  "HND",
                  "HKG",
                  "BLR",
                  "IND",
                  "IDN",
                  "IRQ",
                  "IRN",
                  "IRL",
                  "ISL",
                  "ISR",
                  "ITA",
                  "JAM",
                  "JPN",
                  "YEM",
                  "JEY",
                  "VIR",
                  "VGB",
                  "JOR",
                  "KHM",
                  "CMR",
                  "CPV",
                  "KAZ",
                  "KEN",
                  "CHN",
                  "KGZ",
                  "KIR",
                  "CCK",
                  "COM",
                  "COD",
                  "COG",
                  "HRV",
                  "KWT",
                  "CYP",
                  "LAO",
                  "LVA",
                  "LSO",
                  "LBN",
                  "LBR",
                  "LBY",
                  "LIE",
                  "LTU",
                  "LUX",
                  "MAC",
                  "MDG",
                  "MKD",
                  "MWI",
                  "MYS",
                  "MDV",
                  "MLI",
                  "MLT",
                  "IMN",
                  "MAR",
                  "MHL",
                  "MTQ",
                  "MRT",
                  "MUS",
                  "MYT",
                  "MEX",
                  "FSM",
                  "MDA",
                  "MCO",
                  "MNG",
                  "MNE",
                  "MSR",
                  "MOZ",
                  "MMR",
                  "NAM",
                  "NRU",
                  "NPL",
                  "NLD",
                  "NZL",
                  "NIC",
                  "NER",
                  "NGA",
                  "NIU",
                  "PRK",
                  "MNP",
                  "NFK",
                  "NOR",
                  "NCL",
                  "OMN",
                  "PAK",
                  "PLW",
                  "PAN",
                  "PNG",
                  "PRY",
                  "PER",
                  "PCN",
                  "POL",
                  "PRT",
                  "PRI",
                  "QAT",
                  "REU",
                  "ROU",
                  "RUS",
                  "RWA",
                  "BLM",
                  "SHN",
                  "KNA",
                  "LCA",
                  "MAF",
                  "SPM",
                  "VCT",
                  "SLB",
                  "WSM",
                  "SMR",
                  "STP",
                  "SAU",
                  "SEN",
                  "SRB",
                  "SYC",
                  "SLE",
                  "SGP",
                  "SXM",
                  "SVK",
                  "SVN",
                  "SOM",
                  "ESP",
                  "LKA",
                  "GBR",
                  "SDN",
                  "SUR",
                  "SJM",
                  "CHE",
                  "SWE",
                  "SWZ",
                  "SYR",
                  "ZAF",
                  "SGS",
                  "KOR",
                  "SSD",
                  "TJK",
                  "TWN",
                  "TZA",
                  "THA",
                  "TGO",
                  "TKL",
                  "TON",
                  "TTO",
                  "TCD",
                  "CZE",
                  "TUN",
                  "TKM",
                  "TCA",
                  "TUV",
                  "TUR",
                  "DEU",
                  "UGA",
                  "UKR",
                  "HUN",
                  "URY",
                  "USA",
                  "UMI",
                  "UZB",
                  "VUT",
                  "VAT",
                  "VEN",
                  "ESH",
                  "VNM",
                  "WLF",
                  "ZMB",
                  "ZWE",
                  "AUT",
                  "TLS",
                  "ALA",
                ],
                beskrivendeId: "faktum.eos-arbeidsforhold.land",
                sannsynliggjoresAv: [],
              },
              {
                id: "9005.1",
                svar: "12345",
                type: "tekst",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.eos-arbeidsforhold.personnummer",
                sannsynliggjoresAv: [],
              },
              {
                id: "9006.1",
                svar: {
                  fom: "2022-08-04",
                  tom: "2022-10-01",
                },
                type: "periode",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.eos-arbeidsforhold.varighet",
                sannsynliggjoresAv: [],
              },
            ],
          ],
          type: "generator",
          roller: ["søker"],
          readOnly: false,
          templates: [
            {
              id: "9003",
              type: "tekst",
              roller: ["søker"],
              beskrivendeId: "faktum.eos-arbeidsforhold.arbeidsgivernavn",
            },
            {
              id: "9004",
              type: "land",
              roller: ["søker"],
              beskrivendeId: "faktum.eos-arbeidsforhold.land",
            },
            {
              id: "9005",
              type: "tekst",
              roller: ["søker"],
              beskrivendeId: "faktum.eos-arbeidsforhold.personnummer",
            },
            {
              id: "9006",
              type: "periode",
              roller: ["søker"],
              beskrivendeId: "faktum.eos-arbeidsforhold.varighet",
            },
          ],
          beskrivendeId: "faktum.eos-arbeidsforhold",
        },
      ],
      ferdig: true,
      beskrivendeId: "eos-arbeidsforhold",
    },
    {
      fakta: [
        {
          id: "3001",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.driver-du-egen-naering.svar.ja",
            "faktum.driver-du-egen-naering.svar.nei",
          ],
          beskrivendeId: "faktum.driver-du-egen-naering",
          sannsynliggjoresAv: [
            {
              id: "3016",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokumentasjon-oversikt-over-arbeidstimer",
              sannsynliggjoresAv: [],
            },
          ],
        },
        {
          id: "3002",
          svar: [
            [
              {
                id: "3003.1",
                svar: 123456789,
                type: "int",
                roller: ["søker"],
                readOnly: false,
                beskrivendeId: "faktum.egen-naering-organisasjonsnummer",
                sannsynliggjoresAv: [],
              },
            ],
          ],
          type: "generator",
          roller: ["søker"],
          readOnly: false,
          templates: [
            {
              id: "3003",
              type: "int",
              roller: ["søker"],
              beskrivendeId: "faktum.egen-naering-organisasjonsnummer",
            },
          ],
          beskrivendeId: "faktum.egen-naering-organisasjonsnummer-liste",
        },
        {
          id: "3005",
          svar: 10,
          type: "double",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.egen-naering-arbeidstimer-naa",
          sannsynliggjoresAv: [],
        },
        {
          id: "3004",
          svar: 1,
          type: "double",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.egen-naering-arbeidstimer-for",
          sannsynliggjoresAv: [],
        },
        {
          id: "3006",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.driver-du-eget-gaardsbruk.svar.ja",
            "faktum.driver-du-eget-gaardsbruk.svar.nei",
          ],
          beskrivendeId: "faktum.driver-du-eget-gaardsbruk",
          sannsynliggjoresAv: [
            {
              id: "3016",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId: "faktum.dokumentasjon-oversikt-over-arbeidstimer",
              sannsynliggjoresAv: [],
            },
          ],
        },
        {
          id: "3007",
          svar: 123456789,
          type: "int",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.eget-gaardsbruk-organisasjonsnummer",
          sannsynliggjoresAv: [],
        },
        {
          id: "3008",
          svar: [
            "faktum.eget-gaardsbruk-type-gaardsbruk.svar.dyr",
            "faktum.eget-gaardsbruk-type-gaardsbruk.svar.jord",
            "faktum.eget-gaardsbruk-type-gaardsbruk.svar.skog",
            "faktum.eget-gaardsbruk-type-gaardsbruk.svar.annet",
          ],
          type: "flervalg",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.eget-gaardsbruk-type-gaardsbruk.svar.dyr",
            "faktum.eget-gaardsbruk-type-gaardsbruk.svar.jord",
            "faktum.eget-gaardsbruk-type-gaardsbruk.svar.skog",
            "faktum.eget-gaardsbruk-type-gaardsbruk.svar.annet",
          ],
          beskrivendeId: "faktum.eget-gaardsbruk-type-gaardsbruk",
          sannsynliggjoresAv: [],
        },
        {
          id: "3009",
          svar: ["faktum.eget-gaardsbruk-hvem-eier.svar.selv"],
          type: "flervalg",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.eget-gaardsbruk-hvem-eier.svar.selv",
            "faktum.eget-gaardsbruk-hvem-eier.svar.ektefelle-samboer",
            "faktum.eget-gaardsbruk-hvem-eier.svar.andre",
          ],
          beskrivendeId: "faktum.eget-gaardsbruk-hvem-eier",
          sannsynliggjoresAv: [],
        },
        {
          id: "3010",
          svar: 100,
          type: "double",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.eget-gaardsbruk-jeg-andel-inntekt",
          sannsynliggjoresAv: [],
        },
        {
          id: "3014",
          svar: 2022,
          type: "int",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.eget-gaardsbruk-arbeidsaar-for-timer",
          sannsynliggjoresAv: [],
        },
        {
          id: "3013",
          svar: 1500,
          type: "double",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.eget-gaardsbruk-arbeidstimer-aar",
          sannsynliggjoresAv: [],
        },
        {
          id: "3015",
          svar: "Magi",
          type: "tekst",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.eget-gaardsbruk-arbeidstimer-beregning",
          sannsynliggjoresAv: [],
        },
      ],
      ferdig: true,
      beskrivendeId: "egen-naering",
    },
    {
      fakta: [
        {
          id: "7001",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.avtjent-militaer-sivilforsvar-tjeneste-siste-12-mnd.svar.ja",
            "faktum.avtjent-militaer-sivilforsvar-tjeneste-siste-12-mnd.svar.nei",
          ],
          beskrivendeId: "faktum.avtjent-militaer-sivilforsvar-tjeneste-siste-12-mnd",
          sannsynliggjoresAv: [
            {
              id: "7002",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              beskrivendeId:
                "faktum.avtjent-militaer-sivilforsvar-tjeneste-siste-12-mnd-dokumentasjon",
              sannsynliggjoresAv: [],
            },
          ],
        },
      ],
      ferdig: true,
      beskrivendeId: "verneplikt",
    },
    {
      fakta: [
        {
          id: "5001",
          svar: false,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.andre-ytelser-mottatt-eller-sokt.svar.ja",
            "faktum.andre-ytelser-mottatt-eller-sokt.svar.nei",
          ],
          beskrivendeId: "faktum.andre-ytelser-mottatt-eller-sokt",
          sannsynliggjoresAv: [],
        },
        {
          id: "5012",
          svar: false,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.utbetaling-eller-okonomisk-gode-tidligere-arbeidsgiver.svar.ja",
            "faktum.utbetaling-eller-okonomisk-gode-tidligere-arbeidsgiver.svar.nei",
          ],
          beskrivendeId: "faktum.utbetaling-eller-okonomisk-gode-tidligere-arbeidsgiver",
          sannsynliggjoresAv: [],
        },
      ],
      ferdig: true,
      beskrivendeId: "andre-ytelser",
    },
    {
      fakta: [
        {
          id: "2001",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: ["faktum.tar-du-utdanning.svar.ja", "faktum.tar-du-utdanning.svar.nei"],
          beskrivendeId: "faktum.tar-du-utdanning",
          sannsynliggjoresAv: [],
        },
      ],
      ferdig: true,
      beskrivendeId: "utdanning",
    },
    {
      fakta: [
        {
          id: "1",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: ["faktum.jobbe-hel-deltid.svar.ja", "faktum.jobbe-hel-deltid.svar.nei"],
          beskrivendeId: "faktum.jobbe-hel-deltid",
          sannsynliggjoresAv: [],
        },
        {
          id: "5",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: ["faktum.jobbe-hele-norge.svar.ja", "faktum.jobbe-hele-norge.svar.nei"],
          beskrivendeId: "faktum.jobbe-hele-norge",
          sannsynliggjoresAv: [],
        },
        {
          id: "8",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: ["faktum.alle-typer-arbeid.svar.ja", "faktum.alle-typer-arbeid.svar.nei"],
          beskrivendeId: "faktum.alle-typer-arbeid",
          sannsynliggjoresAv: [],
        },
        {
          id: "9",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.bytte-yrke-ned-i-lonn.svar.ja",
            "faktum.bytte-yrke-ned-i-lonn.svar.nei",
          ],
          beskrivendeId: "faktum.bytte-yrke-ned-i-lonn",
          sannsynliggjoresAv: [],
        },
      ],
      ferdig: true,
      beskrivendeId: "reell-arbeidssoker",
    },
    {
      fakta: [
        {
          id: "4002",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.tilleggsopplysninger.har-tilleggsopplysninger.svar.ja",
            "faktum.tilleggsopplysninger.har-tilleggsopplysninger.svar.nei",
          ],
          beskrivendeId: "faktum.tilleggsopplysninger.har-tilleggsopplysninger",
          sannsynliggjoresAv: [],
        },
        {
          id: "4001",
          svar: "Gi meg penger!",
          type: "tekst",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.tilleggsopplysninger",
          sannsynliggjoresAv: [],
        },
      ],
      ferdig: true,
      beskrivendeId: "tilleggsopplysninger",
    },
  ],
  "@opprettet": "2022-10-03T13:50:42.303604071",
  versjon_id: 234,
  "@event_name": "søker_oppgave",
  søknad_uuid: "ab92f972-2527-45bf-a56a-264a0dd29392",
  versjon_navn: "Dagpenger",
  "@forårsaket_av": {
    id: "0f68dd2d-a6d9-47fd-afed-7426660e3c9f",
    opprettet: "2022-10-03T13:50:41.46503593",
    event_name: "faktum_svar",
  },
  system_read_count: 1,
  system_participating_services: [
    {
      id: "03e6cfa5-de02-4921-98e3-54555aa61db0",
      time: "2022-10-03T13:50:42.329874129",
      image: "ghcr.io/navikt/dp-quiz/dp-quiz-mediator:212ef19d250e7fe40d9ec76f94ead5e29317854f",
      service: "dp-quiz-mediator",
      instance: "dp-quiz-mediator-657f4d866c-bb7jl",
    },
    {
      id: "03e6cfa5-de02-4921-98e3-54555aa61db0",
      time: "2022-10-03T13:50:42.336463214",
      image: "ghcr.io/navikt/dp-soknad:a303a9fc5100c7407d55397014960d25364e765e",
      service: "dp-soknad",
      instance: "dp-soknad-67dc4444bc-c5hs5",
    },
  ],
};
