import { IQuizSeksjon } from "../../types/quiz.types";
import { gyldigeLand } from "./seksjonBostedsland";

export const seksjonArbeidsforhold: IQuizSeksjon = {
  fakta: [
    {
      id: "8001",
      svar: "2022-08-04",
      type: "localdate",
      readOnly: false,
      beskrivendeId: "faktum.dagpenger-soknadsdato",
      sannsynliggjoresAv: [],
      roller: [],
    },
    {
      id: "8002",
      svar: "faktum.type-arbeidstid.svar.fast",
      type: "envalg",
      readOnly: false,
      gyldigeValg: [
        "faktum.type-arbeidstid.svar.fast",
        "faktum.type-arbeidstid.svar.varierende",
        "faktum.type-arbeidstid.svar.kombinasjon",
        "faktum.type-arbeidstid.svar.ingen-passer",
      ],
      beskrivendeId: "faktum.type-arbeidstid",
      sannsynliggjoresAv: [],
      roller: [],
    },
    {
      id: "8003",
      svar: [
        [
          {
            id: "8004.1",
            svar: "as",
            type: "tekst",
            readOnly: false,
            beskrivendeId: "faktum.arbeidsforhold.navn-bedrift",
            sannsynliggjoresAv: [],
            roller: [],
          },
          {
            id: "8005.1",
            svar: "ALB",
            type: "land",
            grupper: [],
            readOnly: false,
            gyldigeLand: gyldigeLand,
            beskrivendeId: "faktum.arbeidsforhold.land",
            sannsynliggjoresAv: [],
            roller: [],
          },
          {
            id: "8006.1",
            svar: "faktum.arbeidsforhold.endret.svar.ikke-endret",
            type: "envalg",
            readOnly: false,
            gyldigeValg: [
              "faktum.arbeidsforhold.endret.svar.ikke-endret",
              "faktum.arbeidsforhold.endret.svar.avskjediget",
              "faktum.arbeidsforhold.endret.svar.sagt-opp-av-arbeidsgiver",
              "faktum.arbeidsforhold.endret.svar.arbeidsgiver-konkurs",
              "faktum.arbeidsforhold.endret.svar.kontrakt-utgaatt",
              "faktum.arbeidsforhold.endret.svar.sagt-opp-selv",
              "faktum.arbeidsforhold.endret.svar.redusert-arbeidstid",
              "faktum.arbeidsforhold.endret.svar.permittert",
            ],
            beskrivendeId: "faktum.arbeidsforhold.endret",
            sannsynliggjoresAv: [],
            roller: [],
          },
          {
            id: "8007.1",
            svar: false,
            type: "boolean",
            readOnly: false,
            gyldigeValg: [
              "faktum.arbeidsforhold.kjent-antall-timer-jobbet.svar.ja",
              "faktum.arbeidsforhold.kjent-antall-timer-jobbet.svar.nei",
            ],
            beskrivendeId: "faktum.arbeidsforhold.kjent-antall-timer-jobbet",
            sannsynliggjoresAv: [],
            roller: [],
          },
          {
            id: "8048.1",
            svar: false,
            type: "boolean",
            readOnly: false,
            gyldigeValg: [
              "faktum.arbeidsforhold.har-tilleggsopplysninger.svar.ja",
              "faktum.arbeidsforhold.har-tilleggsopplysninger.svar.nei",
            ],
            beskrivendeId: "faktum.arbeidsforhold.har-tilleggsopplysninger",
            sannsynliggjoresAv: [],
            roller: [],
          },
        ],
        [
          {
            id: "8004.2",
            svar: "asd",
            type: "tekst",
            readOnly: false,
            beskrivendeId: "faktum.arbeidsforhold.navn-bedrift",
            sannsynliggjoresAv: [],
            roller: [],
          },
          {
            id: "8005.2",
            svar: "AND",
            type: "land",
            grupper: [],
            readOnly: false,
            gyldigeLand: gyldigeLand,
            beskrivendeId: "faktum.arbeidsforhold.land",
            sannsynliggjoresAv: [],
            roller: [],
          },
          {
            id: "8006.2",
            // svar: "faktum.arbeidsforhold.endret.svar.arbeidsgiver-konkurs",
            type: "envalg",
            readOnly: false,
            gyldigeValg: [
              "faktum.arbeidsforhold.endret.svar.ikke-endret",
              "faktum.arbeidsforhold.endret.svar.avskjediget",
              "faktum.arbeidsforhold.endret.svar.sagt-opp-av-arbeidsgiver",
              "faktum.arbeidsforhold.endret.svar.arbeidsgiver-konkurs",
              "faktum.arbeidsforhold.endret.svar.kontrakt-utgaatt",
              "faktum.arbeidsforhold.endret.svar.sagt-opp-selv",
              "faktum.arbeidsforhold.endret.svar.redusert-arbeidstid",
              "faktum.arbeidsforhold.endret.svar.permittert",
            ],
            beskrivendeId: "faktum.arbeidsforhold.endret",
            sannsynliggjoresAv: [],
            roller: [],
          },
          {
            id: "8016.2",
            svar: {
              fom: "2022-08-01",
              tom: "2022-08-06",
            },
            type: "periode",
            readOnly: false,
            beskrivendeId: "faktum.arbeidsforhold.varighet",
            sannsynliggjoresAv: [],
            roller: [],
          },
          {
            id: "8018.2",
            svar: false,
            type: "boolean",
            readOnly: false,
            gyldigeValg: [
              "faktum.arbeidsforhold.vet-du-antall-timer-foer-konkurs.svar.ja",
              "faktum.arbeidsforhold.vet-du-antall-timer-foer-konkurs.svar.nei",
            ],
            beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-konkurs",
            sannsynliggjoresAv: [],
            roller: [],
          },
          {
            id: "8032.2",
            svar: false,
            type: "boolean",
            readOnly: false,
            gyldigeValg: [
              "faktum.arbeidsforhold.soke-forskudd-lonnsgarantimidler.svar.ja",
              "faktum.arbeidsforhold.soke-forskudd-lonnsgarantimidler.svar.nei",
            ],
            beskrivendeId: "faktum.arbeidsforhold.soke-forskudd-lonnsgarantimidler",
            sannsynliggjoresAv: [],
            roller: [],
          },
          {
            id: "8042.2",
            svar: "faktum.arbeidsforhold.midlertidig-arbeidsforhold-med-sluttdato.svar.ja",
            type: "envalg",
            readOnly: false,
            gyldigeValg: [
              "faktum.arbeidsforhold.midlertidig-arbeidsforhold-med-sluttdato.svar.ja",
              "faktum.arbeidsforhold.midlertidig-arbeidsforhold-med-sluttdato.svar.nei",
              "faktum.arbeidsforhold.midlertidig-arbeidsforhold-med-sluttdato.svar.vet-ikke",
            ],
            beskrivendeId: "faktum.arbeidsforhold.midlertidig-arbeidsforhold-med-sluttdato",
            sannsynliggjoresAv: [],
            roller: [],
          },
          {
            id: "8044.2",
            svar: false,
            type: "boolean",
            readOnly: false,
            gyldigeValg: [
              "faktum.arbeidsforhold.skift-eller-turnus.svar.ja",
              "faktum.arbeidsforhold.skift-eller-turnus.svar.nei",
            ],
            beskrivendeId: "faktum.arbeidsforhold.skift-eller-turnus",
            sannsynliggjoresAv: [],
            roller: [],
          },
          {
            id: "8045.2",
            svar: false,
            type: "boolean",
            readOnly: false,
            gyldigeValg: [
              "faktum.arbeidsforhold.rotasjon.svar.ja",
              "faktum.arbeidsforhold.rotasjon.svar.nei",
            ],
            beskrivendeId: "faktum.arbeidsforhold.rotasjon",
            sannsynliggjoresAv: [],
            roller: [],
          },
        ],
      ],
      type: "generator",
      readOnly: false,
      templates: [],
      beskrivendeId: "faktum.arbeidsforhold",
      roller: [],
    },
  ],
  beskrivendeId: "arbeidsforhold",
  ferdig: true,
};
