ingress: https://www.nav.no/arbeid/dagpenger/soknad
base_path: "/arbeid/dagpenger/soknad"
dekorator:
  url: https://www.nav.no/dekoratoren
  env: prod
loginservice:
  url: https://loginservice.nav.no/login
  wellKnown: https://navnob2c.b2clogin.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
sentry_env: production
